// This file was autogenerated by calcdeps.py
goog.addDependency("../../../src/easeljs/display/Bitmap.js", ['Bitmap'], []);
goog.addDependency("../../../src/easeljs/display/BitmapSequence.js", [], []);
goog.addDependency("../../../src/easeljs/display/DisplayObject.js", ['Container', 'DisplayObject', 'Stage'], ['Matrix2D', 'MouseEventPlus', 'Point', 'Shadow', 'UID']);
goog.addDependency("../../../src/easeljs/display/Graphics.js", ['Graphics'], []);
goog.addDependency("../../../src/easeljs/display/Shadow.js", ['Shadow'], []);
goog.addDependency("../../../src/easeljs/display/Shape.js", ['Shape'], ['DisplayObject', 'Graphics']);
goog.addDependency("../../../src/easeljs/display/SpriteSheet.js", ['SpriteSheet'], []);
goog.addDependency("../../../src/easeljs/display/Text.js", ['TextPlus'], []);
goog.addDependency("../../../src/easeljs/events/MouseEventPlus.js", ['MouseEventPlus'], []);
goog.addDependency("../../../src/easeljs/geom/Matrix2D.js", ['Matrix2D'], []);
goog.addDependency("../../../src/easeljs/geom/Point.js", ['Point'], ['goog.math.Coordinate']);
goog.addDependency("../../../src/easeljs/geom/Rectangle.js", [], []);
goog.addDependency("../../../src/easeljs/utils/SpriteSheetUtils.js", [], []);
goog.addDependency("../../../src/easeljs/utils/Ticker.js", ['Ticker'], []);
goog.addDependency("../../../src/easeljs/utils/UID.js", ['UID'], []);
