/**
* EaselJS
* Visit http://easeljs.com/ for documentation, updates and examples.
*
* Copyright (c) 2011 Grant Skinner
* 
* Permission is hereby granted, free of charge, to any person
* obtaining a copy of this software and associated documentation
* files (the "Software"), to deal in the Software without
* restriction, including without limitation the rights to use,
* copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the
* Software is furnished to do so, subject to the following
* conditions:
* 
* The above copyright notice and this permission notice shall be
* included in all copies or substantial portions of the Software.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
* OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
* HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
* WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
* FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
**/
(function(m){var e=function(){throw"UID cannot be instantiated";};e._nextID=0;e.get=function(){return e._nextID++};m.UID=e})(window);(function(m){var e=function(){throw"Ticker cannot be instantiated.";};e.useRAF=null;e._listeners=null;e._pauseable=null;e._paused=false;e._inited=false;e._startTime=0;e._pausedTime=0;e._ticks=0;e._pausedTickers=0;e._interval=50;e._lastTime=0;e._times=null;e._tickTimes=null;e._rafActive=false;e.addListener=function(b,a){e._inited||e.init();e.removeListener(b);e._pauseable[e._listeners.length]=a==null?true:a;e._listeners.push(b)};e.init=function(){e._inited=true;e._times=[];e._tickTimes=[];e._pauseable=
[];e._listeners=[];e._times.push(e._startTime=e._getTime());e.setInterval(e._interval)};e.removeListener=function(b){if(e._listeners!=null){b=e._listeners.indexOf(b);if(b!=-1){e._listeners.splice(b,1);e._pauseable.splice(b,1)}}};e.removeAllListeners=function(){e._listeners=[];e._pauseable=[]};e.setInterval=function(b){e._lastTime=e._getTime();e._interval=b;if(e.useRAF){var a=m.requestAnimationFrame||m.webkitRequestAnimationFrame||m.mozRequestAnimationFrame||m.oRequestAnimationFrame||m.msRequestAnimationFrame;
if(a){a(e._handleAF);e._rafFunction=a;return}}this._inited&&setTimeout(e._handleTimeout,b)};e.getInterval=function(){return e._interval};e.setFPS=function(b){e.setInterval(1E3/b)};e.getFPS=function(){return 1E3/e._interval};e.getMeasuredFPS=function(b){if(e._times.length<2)return-1;if(b==null)b=e.getFPS()>>1;b=Math.min(e._times.length-1,b);return 1E3/((e._times[0]-e._times[b])/b)};e.setPaused=function(b){e._paused=b};e.getPaused=function(){return e._paused};e.getTime=function(b){return e._getTime()-
e._startTime-(b?e._pausedTime:0)};e.getTicks=function(b){return e._ticks-(b?e._pausedTickers:0)};e._handleAF=function(b){console.log(e._rafFunction);b-e._lastTime>=e._interval-1&&e._tick();(m.requestAnimationFrame||m.webkitRequestAnimationFrame||m.mozRequestAnimationFrame||m.oRequestAnimationFrame||m.msRequestAnimationFrame)(e._handleAF,e.animationTarget)};e._handleTimeout=function(){e._tick();setTimeout(e._handleTimeout,e._interval)};e._tick=function(){e._ticks++;var b=e._getTime(),a=b-e._lastTime,
c=e._paused;if(c){e._pausedTickers++;e._pausedTime+=a}e._lastTime=b;for(var d=e._pauseable,f=e._listeners.slice(),g=f?f.length:0,h=0;h<g;h++){var i=d[h],k=f[h];k==null||c&&i||k.tick==null||k.tick(a,c)}for(e._tickTimes.unshift(e._getTime()-b);e._tickTimes.length>100;)e._tickTimes.pop();for(e._times.unshift(b);e._times.length>100;)e._times.pop()};e._getTime=function(){return(new Date).getTime()};m.Ticker=e})(window);(function(m){var e=function(a,c,d,f,g){this.initialize(a,c,d,f,g)},b=e.prototype;b.stageX=0;b.stageY=0;b.type=null;b.nativeEvent=null;b.onMouseMove=null;b.onMouseUp=null;b.target=null;b.initialize=function(a,c,d,f,g){this.type=a;this.stageX=c;this.stageY=d;this.target=f;this.nativeEvent=g};b.clone=function(){return new e(this.type,this.stageX,this.stageY,this.target,this.nativeEvent)};b.toString=function(){return"[MouseEvent (type="+this.type+" stageX="+this.stageX+" stageY="+this.stageY+")]"};m.MouseEvent=
e})(window);(function(m){var e=function(a,c,d,f,g,h){this.initialize(a,c,d,f,g,h)},b=e.prototype;e.identity=null;e.DEG_TO_RAD=Math.PI/180;b.a=1;b.b=0;b.c=0;b.d=1;b.tx=0;b.ty=0;b.alpha=1;b.shadow=null;b.compositeOperation=null;b.initialize=function(a,c,d,f,g,h){if(a!=null)this.a=a;this.b=c||0;this.c=d||0;if(f!=null)this.d=f;this.tx=g||0;this.ty=h||0};b.prepend=function(a,c,d,f,g,h){var i=this.tx;if(a!=1||c!=0||d!=0||f!=1){var k=this.a,j=this.c;this.a=k*a+this.b*d;this.b=k*c+this.b*f;this.c=j*a+this.d*d;this.d=
j*c+this.d*f}this.tx=i*a+this.ty*d+g;this.ty=i*c+this.ty*f+h};b.append=function(a,c,d,f,g,h){var i=this.a,k=this.b,j=this.c,l=this.d;this.a=a*i+c*j;this.b=a*k+c*l;this.c=d*i+f*j;this.d=d*k+f*l;this.tx=g*i+h*j+this.tx;this.ty=g*k+h*l+this.ty};b.prependMatrix=function(a){this.prepend(a.a,a.b,a.c,a.d,a.tx,a.ty);this.prependProperties(a.alpha,a.shadow,a.compositeOperation)};b.appendMatrix=function(a){this.append(a.a,a.b,a.c,a.d,a.tx,a.ty);this.appendProperties(a.alpha,a.shadow,a.compositeOperation)};
b.prependTransform=function(a,c,d,f,g,h,i,k,j){if(g%360){var l=g*e.DEG_TO_RAD;g=Math.cos(l);l=Math.sin(l)}else{g=1;l=0}if(k||j){this.tx-=k;this.ty-=j}if(h||i){h*=e.DEG_TO_RAD;i*=e.DEG_TO_RAD;this.prepend(g*d,l*d,-l*f,g*f,0,0);this.prepend(Math.cos(i),Math.sin(i),-Math.sin(h),Math.cos(h),a,c)}else this.prepend(g*d,l*d,-l*f,g*f,a,c)};b.appendTransform=function(a,c,d,f,g,h,i,k,j){if(g%360){var l=g*e.DEG_TO_RAD;g=Math.cos(l);l=Math.sin(l)}else{g=1;l=0}if(h||i){h*=e.DEG_TO_RAD;i*=e.DEG_TO_RAD;this.append(Math.cos(i),
Math.sin(i),-Math.sin(h),Math.cos(h),a,c);this.append(g*d,l*d,-l*f,g*f,0,0)}else this.append(g*d,l*d,-l*f,g*f,a,c);if(k||j){this.tx-=k*this.a+j*this.c;this.ty-=k*this.b+j*this.d}};b.rotate=function(a){var c=Math.cos(a);a=Math.sin(a);var d=this.a,f=this.c,g=this.tx;this.a=d*c-this.b*a;this.b=d*a+this.b*c;this.c=f*c-this.d*a;this.d=f*a+this.d*c;this.tx=g*c-this.ty*a;this.ty=g*a+this.ty*c};b.skew=function(a,c){a*=e.DEG_TO_RAD;c*=e.DEG_TO_RAD;this.append(Math.cos(c),Math.sin(c),-Math.sin(a),Math.cos(a),
0,0)};b.scale=function(a,c){this.a*=a;this.d*=c;this.tx*=a;this.ty*=c};b.translate=function(a,c){this.tx+=a;this.ty+=c};b.identity=function(){this.alpha=this.a=this.d=1;this.b=this.c=this.tx=this.ty=0;this.shadow=this.compositeOperation=null};b.invert=function(){var a=this.a,c=this.b,d=this.c,f=this.d,g=this.tx,h=a*f-c*d;this.a=f/h;this.b=-c/h;this.c=-d/h;this.d=a/h;this.tx=(d*this.ty-f*g)/h;this.ty=-(a*this.ty-c*g)/h};b.isIdentity=function(){return this.tx==0&&this.ty==0&&this.a==1&&this.b==0&&this.c==
0&&this.d==1};b.decompose=function(a){if(a==null)a={};a.x=this.tx;a.y=this.ty;a.scaleX=Math.sqrt(this.a*this.a+this.b*this.b);a.scaleY=Math.sqrt(this.c*this.c+this.d*this.d);var c=Math.atan2(-this.c,this.d),d=Math.atan2(this.b,this.a);if(c==d){a.rotation=d/e.DEG_TO_RAD;if(this.a<0&&this.d>=0)a.rotation+=a.rotation<=0?180:-180;a.skewX=a.skewY=0}else{a.skewX=c/e.DEG_TO_RAD;a.skewY=d/e.DEG_TO_RAD}return a};b.reinitialize=function(a,c,d,f,g,h,i,k,j){this.initialize(a,c,d,f,g,h);this.alpha=i||1;this.shadow=
k;this.compositeOperation=j;return this};b.appendProperties=function(a,c,d){this.alpha*=a;this.shadow=c||this.shadow;this.compositeOperation=d||this.compositeOperation};b.prependProperties=function(a,c,d){this.alpha*=a;this.shadow=this.shadow||c;this.compositeOperation=this.compositeOperation||d};b.clone=function(){var a=new e(this.a,this.b,this.c,this.d,this.tx,this.ty);a.shadow=this.shadow;a.alpha=this.alpha;a.compositeOperation=this.compositeOperation;return a};b.toString=function(){return"[Matrix2D (a="+
this.a+" b="+this.b+" c="+this.c+" d="+this.d+" tx="+this.tx+" ty="+this.ty+")]"};e.identity=new e(1,0,0,1,0,0);m.Matrix2D=e})(window);(function(m){var e=function(a,c){this.initialize(a,c)},b=e.prototype;b.x=0;b.y=0;b.initialize=function(a,c){this.x=a==null?0:a;this.y=c==null?0:c};b.clone=function(){return new e(this.x,this.y)};b.toString=function(){return"[Point (x="+this.x+" y="+this.y+")]"};m.Point=e})(window);(function(m){var e=function(a,c,d,f){this.initialize(a,c,d,f)},b=e.prototype;b.x=0;b.y=0;b.width=0;b.height=0;b.initialize=function(a,c,d,f){this.x=a==null?0:a;this.y=c==null?0:c;this.width=d==null?0:d;this.height=f==null?0:f};b.clone=function(){return new e(this.x,this.y,this.width,this.height)};b.toString=function(){return"[Rectangle (x="+this.x+" y="+this.y+" width="+this.width+" height="+this.height+")]"};m.Rectangle=e})(window);(function(m){var e=function(a,c,d,f){this.initialize(a,c,d,f)},b=e.prototype;e.identity=null;b.color=null;b.offsetX=0;b.offsetY=0;b.blur=0;b.initialize=function(a,c,d,f){this.color=a;this.offsetX=c;this.offsetY=d;this.blur=f};b.toString=function(){return"[Shadow]"};b.clone=function(){return new e(this.color,this.offsetX,this.offsetY,this.blur)};e.identity=new e("transparent",0,0,0);m.Shadow=e})(window);(function(m){var e=function(a){this.initialize(a)},b=e.prototype;b.complete=true;b._animations=null;b._frames=null;b._images=null;b._data=null;b._loadCount=0;b._frameHeight=0;b._frameWidth=0;b._numFrames=0;b._regX=0;b._regY=0;b.initialize=function(a){var c,d,f;if(a!=null){if(a.images&&(d=a.images.length)>0){f=this._images=[];for(c=0;c<d;c++){var g=a.images[c];if(!(g instanceof Image)){var h=g;g=new Image;g.src=h}f.push(g);if(!g.getContext&&!g.complete){this._loadCount++;this.complete=false;g.onload=
this._handleImageLoad()}}}if(a.frames!=null)if(a.frames instanceof Array){this._frames=[];f=a.frames;c=0;for(d=f.length;c<d;c++){g=f[c];this._frames.push({image:this._images[g[4]?g[4]:0],rect:new Rectangle(g[0],g[1],g[2],g[3]),regX:g[4]||0,regY:g[5]||0})}}else{d=a.frames;this._frameWidth=d.frameWidth;this._frameHeight=d.frameHeight;this._regX=d.regX||0;this._regY=d.regY||0;this._numFrames=d.numFrames;this._loadCount==0&&this._calculateFrames()}if((d=a.animations)!=null){this._animations=[];this._data=
{};for(var i in d){a={name:i};g=d[i];if(!isNaN(g))a.frames=[g];if(g instanceof Array){a.frequency=g[3];a.next=g[2];f=a.frames=[];for(c=g[0];c<=g[1];c++)f.push(c)}else{a.frequency=g.frequency;a.next=g.next;f=a.frames=g.frames.slice(0)}a.next=f.length<2?null:!a.next||a.next==true?i:a.next;if(!a.frequency)a.frequency=1;this._animations.push(i);this._data[i]=a}}}};b.getNumFrames=function(a){if(a==null)return this._frames?this._frames.length:this._numFrames;else{a=this._data[a];return a==null?0:a.frames.length}};
b.getAnimations=function(){return this._animations.slice(0)};b.getAnimation=function(a){return this._data[a]};b.getFrameRect=function(a){if(this.complete&&this._frames&&(frame=this._frames[a]))return frame;return null};b.toString=function(){return"[SpriteSheet]"};b.clone=function(){var a=new e;a.complete=this.complete;a._animations=this._animations;a._frames=this._frames;a._images=this._images;a._data=this._data;a._frameHeight=this._frameHeight;a._frameWidth=this._frameWidth;a._numFrames=this._numFrames;
a._loadCount=this._loadCount;return a};b._handleImageLoad=function(){if(--this._loadCount==0){this._calculateFrames();this.complete=true}};b._calculateFrames=function(){if(!(this._frames||this._frameWidth==0)){this._frames=[];for(var a=0,c=this._frameWidth,d=this._frameHeight,f=0,g=this._images;f<g.length;f++){var h=g[f],i=(h.width+1)/c|0,k=(h.height+1)/d|0;k=this._numFrames>0?Math.min(this._numFrames-a,i*k):i*k;for(var j=0;j<k;j++)this._frames.push({image:h,rect:new Rectangle(j%i*c,(j/i|0)*d,c,d),
regX:this._regX,regY:this._regY});a+=k}this._numFrames=a}};m.SpriteSheet=e})(window);(function(m){function e(c,d){this.f=c;this.params=d}e.prototype.exec=function(c){this.f.apply(c,this.params)};var b=function(){this.initialize()},a=b.prototype;b.getRGB=function(c,d,f,g){if(c!=null&&f==null){g=d;f=c&255;d=c>>8&255;c=c>>16&255}return g==null?"rgb("+c+","+d+","+f+")":"rgba("+c+","+d+","+f+","+g+")"};b.getHSL=function(c,d,f,g){return g==null?"hsl("+c%360+","+d+"%,"+f+"%)":"hsla("+c%360+","+d+"%,"+f+"%,"+g+")"};b.STROKE_CAPS_MAP=["butt","round","square"];b.STROKE_JOINTS_MAP=["miter",
"round","bevel"];b._ctx=document.createElement("canvas").getContext("2d");b.beginCmd=new e(b._ctx.beginPath,[]);b.fillCmd=new e(b._ctx.fill,[]);b.strokeCmd=new e(b._ctx.stroke,[]);a._strokeInstructions=null;a._strokeStyleInstructions=null;a._fillInstructions=null;a._instructions=null;a._oldInstructions=null;a._activeInstructions=null;a._active=false;a._dirty=false;a.initialize=function(){this.clear();this._ctx=b._ctx};a.draw=function(c){this._dirty&&this._updateInstructions();for(var d=this._instructions,
f=0,g=d.length;f<g;f++)d[f].exec(c)};a.moveTo=function(c,d){this._activeInstructions.push(new e(this._ctx.moveTo,[c,d]));return this};a.lineTo=function(c,d){this._dirty=this._active=true;this._activeInstructions.push(new e(this._ctx.lineTo,[c,d]));return this};a.arcTo=function(c,d,f,g,h){this._dirty=this._active=true;this._activeInstructions.push(new e(this._ctx.arcTo,[c,d,f,g,h]));return this};a.arc=function(c,d,f,g,h,i){this._dirty=this._active=true;if(i==null)i=false;this._activeInstructions.push(new e(this._ctx.arc,
[c,d,f,g,h,i]));return this};a.quadraticCurveTo=function(c,d,f,g){this._dirty=this._active=true;this._activeInstructions.push(new e(this._ctx.quadraticCurveTo,[c,d,f,g]));return this};a.bezierCurveTo=function(c,d,f,g,h,i){this._dirty=this._active=true;this._activeInstructions.push(new e(this._ctx.bezierCurveTo,[c,d,f,g,h,i]));return this};a.rect=function(c,d,f,g){this._dirty=this._active=true;this._activeInstructions.push(new e(this._ctx.rect,[c,d,f,g]));return this};a.closePath=function(){if(this._active){this._dirty=
true;this._activeInstructions.push(new e(this._ctx.closePath,[]))}return this};a.clear=function(){this._instructions=[];this._oldInstructions=[];this._activeInstructions=[];this._strokeStyleInstructions=this._strokeInstructions=this._fillInstructions=null;this._active=this._dirty=false;return this};a.beginFill=function(c){this._active&&this._newPath();this._fillInstructions=c?[new e(this._setProp,["fillStyle",c])]:null;return this};a.beginLinearGradientFill=function(c,d,f,g,h,i){this._active&&this._newPath();
f=this._ctx.createLinearGradient(f,g,h,i);g=0;for(h=c.length;g<h;g++)f.addColorStop(d[g],c[g]);this._fillInstructions=[new e(this._setProp,["fillStyle",f])];return this};a.beginRadialGradientFill=function(c,d,f,g,h,i,k,j){this._active&&this._newPath();f=this._ctx.createRadialGradient(f,g,h,i,k,j);g=0;for(h=c.length;g<h;g++)f.addColorStop(d[g],c[g]);this._fillInstructions=[new e(this._setProp,["fillStyle",f])];return this};a.beginBitmapFill=function(c,d){this._active&&this._newPath();var f=this._ctx.createPattern(c,
d||"");this._fillInstructions=[new e(this._setProp,["fillStyle",f])];return this};a.endFill=function(){this.beginFill(null);return this};a.setStrokeStyle=function(c,d,f,g){this._active&&this._newPath();this._strokeStyleInstructions=[new e(this._setProp,["lineWidth",c==null?"1":c]),new e(this._setProp,["lineCap",d==null?"butt":isNaN(d)?d:b.STROKE_CAPS_MAP[d]]),new e(this._setProp,["lineJoin",f==null?"miter":isNaN(f)?f:b.STROKE_JOINTS_MAP[f]]),new e(this._setProp,["miterLimit",g==null?"10":g])];return this};
a.beginStroke=function(c){this._active&&this._newPath();this._strokeInstructions=c?[new e(this._setProp,["strokeStyle",c])]:null;return this};a.beginLinearGradientStroke=function(c,d,f,g,h,i){this._active&&this._newPath();f=this._ctx.createLinearGradient(f,g,h,i);g=0;for(h=c.length;g<h;g++)f.addColorStop(d[g],c[g]);this._strokeInstructions=[new e(this._setProp,["strokeStyle",f])];return this};a.beginRadialGradientStroke=function(c,d,f,g,h,i,k,j){this._active&&this._newPath();f=this._ctx.createRadialGradient(f,
g,h,i,k,j);g=0;for(h=c.length;g<h;g++)f.addColorStop(d[g],c[g]);this._strokeInstructions=[new e(this._setProp,["strokeStyle",f])];return this};a.beginBitmapStroke=function(c,d){this._active&&this._newPath();var f=this._ctx.createPattern(c,d||"");this._strokeInstructions=[new e(this._setProp,["strokeStyle",f])];return this};a.endStroke=function(){this.beginStroke(null);return this};a.curveTo=a.quadraticCurveTo;a.drawRect=a.rect;a.drawRoundRect=function(c,d,f,g,h){this.drawRoundRectComplex(c,d,f,g,
h,h,h,h);return this};a.drawRoundRectComplex=function(c,d,f,g,h,i,k,j){this._dirty=this._active=true;this._activeInstructions.push(new e(this._ctx.moveTo,[c+h,d]),new e(this._ctx.lineTo,[c+f-i,d]),new e(this._ctx.arc,[c+f-i,d+i,i,-Math.PI/2,0,false]),new e(this._ctx.lineTo,[c+f,d+g-k]),new e(this._ctx.arc,[c+f-k,d+g-k,k,0,Math.PI/2,false]),new e(this._ctx.lineTo,[c+j,d+g]),new e(this._ctx.arc,[c+j,d+g-j,j,Math.PI/2,Math.PI,false]),new e(this._ctx.lineTo,[c,d+h]),new e(this._ctx.arc,[c+h,d+h,h,Math.PI,
Math.PI*3/2,false]));return this};a.drawCircle=function(c,d,f){this.arc(c,d,f,0,Math.PI*2);return this};a.drawEllipse=function(c,d,f,g){this._dirty=this._active=true;var h=f/2*0.5522848,i=g/2*0.5522848,k=c+f,j=d+g;f=c+f/2;g=d+g/2;this._activeInstructions.push(new e(this._ctx.moveTo,[c,g]),new e(this._ctx.bezierCurveTo,[c,g-i,f-h,d,f,d]),new e(this._ctx.bezierCurveTo,[f+h,d,k,g-i,k,g]),new e(this._ctx.bezierCurveTo,[k,g+i,f+h,j,f,j]),new e(this._ctx.bezierCurveTo,[f-h,j,c,g+i,c,g]));return this};a.drawPolyStar=
function(c,d,f,g,h,i){this._dirty=this._active=true;if(h==null)h=0;h=1-h;if(i==null)i=0;else i/=180/Math.PI;var k=Math.PI/g;this._activeInstructions.push(new e(this._ctx.moveTo,[c+Math.cos(i)*f,d+Math.sin(i)*f]));for(var j=0;j<g;j++){i+=k;h!=1&&this._activeInstructions.push(new e(this._ctx.lineTo,[c+Math.cos(i)*f*h,d+Math.sin(i)*f*h]));i+=k;this._activeInstructions.push(new e(this._ctx.lineTo,[c+Math.cos(i)*f,d+Math.sin(i)*f]))}return this};a.clone=function(){var c=new b;c._instructions=this._instructions.slice();
c._activeInstructions=this._activeInstructions.slice();c._oldInstructions=this._oldInstructions.slice();if(this._fillInstructions)c._fillInstructions=this._fillInstructions.slice();if(this._strokeInstructions)c._strokeInstructions=this._strokeInstructions.slice();if(this._strokeStyleInstructions)c._strokeStyleInstructions=this._strokeStyleInstructions.slice();c._active=this._active;c._dirty=this._dirty;return c};a.toString=function(){return"[Graphics]"};a.mt=a.moveTo;a.lt=a.lineTo;a.at=a.arcTo;a.bt=
a.bezierCurveTo;a.qt=a.quadraticCurveTo;a.a=a.arc;a.r=a.rect;a.cp=a.closePath;a.c=a.clear;a.f=a.beginFill;a.lf=a.beginLinearGradientFill;a.rf=a.beginRadialGradientFill;a.bf=a.beginBitmapFill;a.ef=a.endFill;a.ss=a.setStrokeStyle;a.s=a.beginStroke;a.ls=a.beginLinearGradientStroke;a.rs=a.beginRadialGradientStroke;a.bs=a.beginBitmapStroke;a.es=a.endStroke;a.dr=a.drawRect;a.rr=a.drawRoundRect;a.rc=a.drawRoundRectComplex;a.dc=a.drawCircle;a.de=a.drawEllipse;a.dp=a.drawPolyStar;a._updateInstructions=function(){this._instructions=
this._oldInstructions.slice();this._instructions.push(b.beginCmd);this._fillInstructions&&this._instructions.push.apply(this._instructions,this._fillInstructions);if(this._strokeInstructions){this._instructions.push.apply(this._instructions,this._strokeInstructions);this._strokeStyleInstructions&&this._instructions.push.apply(this._instructions,this._strokeStyleInstructions)}this._instructions.push.apply(this._instructions,this._activeInstructions);this._fillInstructions&&this._instructions.push(b.fillCmd);
this._strokeInstructions&&this._instructions.push(b.strokeCmd)};a._newPath=function(){this._dirty&&this._updateInstructions();this._oldInstructions=this._instructions;this._activeInstructions=[];this._active=this._dirty=false};a._setProp=function(c,d){this[c]=d};m.Graphics=b})(window);(function(m){var e=function(){this.initialize()},b=e.prototype;e.suppressCrossDomainErrors=false;e._hitTestCanvas=document.createElement("canvas");e._hitTestCanvas.width=e._hitTestCanvas.height=1;e._hitTestContext=e._hitTestCanvas.getContext("2d");b.alpha=1;b.cacheCanvas=null;b.id=-1;b.mouseEnabled=true;b.name=null;b.parent=null;b.regX=0;b.regY=0;b.rotation=0;b.scaleX=1;b.scaleY=1;b.skewX=0;b.skewY=0;b.shadow=null;b.visible=true;b.x=0;b.y=0;b.compositeOperation=null;b.snapToPixel=false;b.onPress=
null;b.onClick=null;b.onDoubleClick=null;b.onMouseOver=null;b.onMouseOut=null;b.tick=null;b.filters=null;b._cacheOffsetX=0;b._cacheOffsetY=0;b._matrix=null;b.initialize=function(){this.id=UID.get();this._matrix=new Matrix2D};b.isVisible=function(){return this.visible&&this.alpha>0&&this.scaleX!=0&&this.scaleY!=0};b.draw=function(a,c){if(c||!this.cacheCanvas)return false;a.drawImage(this.cacheCanvas,this._cacheOffsetX,this._cacheOffsetY);return true};b.cache=function(a,c,d,f){if(this.cacheCanvas==
null)this.cacheCanvas=document.createElement("canvas");var g=this.cacheCanvas.getContext("2d");this.cacheCanvas.width=d;this.cacheCanvas.height=f;g.setTransform(1,0,0,1,-a,-c);g.clearRect(0,0,d+1,f+1);this.draw(g,true);this._cacheOffsetX=a;this._cacheOffsetY=c;this._applyFilters()};b.updateCache=function(a){if(this.cacheCanvas==null)throw"cache() must be called before updateCache()";var c=this.cacheCanvas.getContext("2d");c.setTransform(1,0,0,1,-this._cacheOffsetX,-this._cacheOffsetY);if(a)c.globalCompositeOperation=
a;else c.clearRect(0,0,this.cacheCanvas.width+1,this.cacheCanvas.height+1);this.draw(c,true);if(a)c.globalCompositeOperation="source-over";this._applyFilters()};b.uncache=function(){this.cacheCanvas=null;this._cacheOffsetX=this._cacheOffsetY=0};b.getStage=function(){for(var a=this;a.parent;)a=a.parent;if(a instanceof Stage)return a;return null};b.localToGlobal=function(a,c){var d=this.getConcatenatedMatrix(this._matrix);if(d==null)return null;d.append(1,0,0,1,a,c);return new Point(d.tx,d.ty)};b.globalToLocal=
function(a,c){var d=this.getConcatenatedMatrix(this._matrix);if(d==null)return null;d.invert();d.append(1,0,0,1,a,c);return new Point(d.tx,d.ty)};b.localToLocal=function(a,c,d){a=this.localToGlobal(a,c);return d.globalToLocal(a.x,a.y)};b.setTransform=function(a,c,d,f,g,h,i,k,j){this.x=a||0;this.y=c||0;this.scaleX=d==null?1:d;this.scaleY=f==null?1:f;this.rotation=g||0;this.skewX=h||0;this.skewY=i||0;this.regX=k||0;this.regY=j||0};b.getConcatenatedMatrix=function(a){if(a)a.identity();else a=new Matrix2D;
for(var c=this;c!=null;){a.prependTransform(c.x,c.y,c.scaleX,c.scaleY,c.rotation,c.skewX,c.skewY,c.regX,c.regY);a.prependProperties(c.alpha,c.shadow,c.compositeOperation);c=c.parent}return a};b.hitTest=function(a,c){var d=e._hitTestContext,f=e._hitTestCanvas;d.setTransform(1,0,0,1,-a,-c);this.draw(d);d=this._testHit(d);f.width=0;f.width=1;return d};b.clone=function(){var a=new e;this.cloneProps(a);return a};b.toString=function(){return"[DisplayObject (name="+this.name+")]"};b.cloneProps=function(a){a.alpha=
this.alpha;a.name=this.name;a.regX=this.regX;a.regY=this.regY;a.rotation=this.rotation;a.scaleX=this.scaleX;a.scaleY=this.scaleY;a.shadow=this.shadow;a.skewX=this.skewX;a.skewY=this.skewY;a.visible=this.visible;a.x=this.x;a.y=this.y;a.mouseEnabled=this.mouseEnabled;a.compositeOperation=this.compositeOperation};b.applyShadow=function(a,c){c=c||Shadow.identity;a.shadowColor=c.color;a.shadowOffsetX=c.offsetX;a.shadowOffsetY=c.offsetY;a.shadowBlur=c.blur};b._testHit=function(a){try{var c=a.getImageData(0,
0,1,1).data[3]>1}catch(d){if(!e.suppressCrossDomainErrors)throw"An error has occured. This is most likely due to security restrictions on reading canvas pixel data with local or cross-domain images.";}return c};b._applyFilters=function(){if(!(!this.filters||this.filters.length==0||!this.cacheCanvas))for(var a=this.filters.length,c=this.cacheCanvas.getContext("2d"),d=this.cacheCanvas.width,f=this.cacheCanvas.height,g=0;g<a;g++)this.filters[g].applyFilter(c,0,0,d,f)};m.DisplayObject=e})(window);(function(m){var e=function(){this.initialize()},b=e.prototype=new DisplayObject;b.children=null;b.DisplayObject_initialize=b.initialize;b.initialize=function(){this.DisplayObject_initialize();this.children=[]};b.isVisible=function(){return this.visible&&this.alpha>0&&this.children.length&&this.scaleX!=0&&this.scaleY!=0};b.DisplayObject_draw=b.draw;b.draw=function(a,c,d){var f=Stage._snapToPixelEnabled;if(this.DisplayObject_draw(a,c))return true;d=d||this._matrix.reinitialize(1,0,0,1,0,0,this.alpha,
this.shadow,this.compositeOperation);c=this.children.length;for(var g=this.children.slice(0),h=0;h<c;h++){var i=g[h];if(i.isVisible()){var k=false,j=i._matrix.reinitialize(d.a,d.b,d.c,d.d,d.tx,d.ty,d.alpha,d.shadow,d.compositeOperation);j.appendTransform(i.x,i.y,i.scaleX,i.scaleY,i.rotation,i.skewX,i.skewY,i.regX,i.regY);j.appendProperties(i.alpha,i.shadow,i.compositeOperation);if(!(i instanceof e&&i.cacheCanvas==null)){f&&i.snapToPixel&&j.a==1&&j.b==0&&j.c==0&&j.d==1?a.setTransform(j.a,j.b,j.c,j.d,
j.tx+0.5|0,j.ty+0.5|0):a.setTransform(j.a,j.b,j.c,j.d,j.tx,j.ty);a.globalAlpha=j.alpha;a.globalCompositeOperation=j.compositeOperation||"source-over";if(k=j.shadow)this.applyShadow(a,k)}i.draw(a,false,j);k&&this.applyShadow(a)}}return true};b.addChild=function(a){var c=arguments.length;if(c>1){for(var d=0;d<c;d++)this.addChild(arguments[d]);return arguments[c-1]}a.parent&&a.parent.removeChild(a);a.parent=this;this.children.push(a);return a};b.addChildAt=function(a,c){var d=arguments.length;if(d>2){c=
arguments[f-1];for(var f=0;f<d-1;f++)this.addChildAt(arguments[f],c+f);return arguments[d-2]}a.parent&&a.parent.removeChild(a);a.parent=this;this.children.splice(c,0,a);return a};b.removeChild=function(a){var c=arguments.length;if(c>1){for(var d=true,f=0;f<c;f++)d=d&&this.removeChild(arguments[f]);return d}return this.removeChildAt(this.children.indexOf(a))};b.removeChildAt=function(a){var c=arguments.length;if(c>1){for(var d=[],f=0;f<c;f++)d[f]=arguments[f];d.sort(function(h,i){return i-h});var g=
true;for(f=0;f<c;f++)g=g&&this.removeChildAt(d[f]);return g}if(a<0||a>this.children.length-1)return false;c=this.children[a];if(c!=null)c.parent=null;this.children.splice(a,1);return true};b.removeAllChildren=function(){for(;this.children.length;)this.removeChildAt(0)};b.getChildAt=function(a){return this.children[a]};b.sortChildren=function(a){this.children.sort(a)};b.getChildIndex=function(a){return this.children.indexOf(a)};b.getNumChildren=function(){return this.children.length};b.contains=function(a){for(;a;){if(a==
this)return true;a=a.parent}return false};b.hitTest=function(a,c){return this.getObjectUnderPoint(a,c)!=null};b.getObjectsUnderPoint=function(a,c){var d=[],f=this.localToGlobal(a,c);this._getObjectsUnderPoint(f.x,f.y,d);return d};b.getObjectUnderPoint=function(a,c){var d=this.localToGlobal(a,c);return this._getObjectsUnderPoint(d.x,d.y)};b.clone=function(a){var c=new e;this.cloneProps(c);if(a)for(var d=c.children=[],f=0,g=this.children.length;f<g;f++){var h=this.children[f].clone(a);h.parent=c;d.push(h)}return c};
b.toString=function(){return"[Container (name="+this.name+")]"};b._tick=function(){for(var a=this.children.length-1;a>=0;a--){var c=this.children[a];c._tick&&c._tick();c.tick&&c.tick()}};b._getObjectsUnderPoint=function(a,c,d,f){var g=DisplayObject._hitTestContext,h=DisplayObject._hitTestCanvas,i=this._matrix,k=f&1&&(this.onPress||this.onClick||this.onDoubleClick)||f&2&&(this.onMouseOver||this.onMouseOut);if(this.cacheCanvas){this.getConcatenatedMatrix(i);g.setTransform(i.a,i.b,i.c,i.d,i.tx-a,i.ty-
c);g.globalAlpha=i.alpha;this.draw(g);if(this._testHit(g)){h.width=0;h.width=1;if(k)return this}else return null}for(var j=this.children.length-1;j>=0;j--){var l=this.children[j];if(l.isVisible()&&l.mouseEnabled)if(l instanceof e)if(k){if(l=l._getObjectsUnderPoint(a,c))return this}else{l=l._getObjectsUnderPoint(a,c,d,f);if(!d&&l)return l}else if(!f||k||f&1&&(l.onPress||l.onClick||l.onDoubleClick)||f&2&&(l.onMouseOver||l.onMouseOut)){l.getConcatenatedMatrix(i);g.setTransform(i.a,i.b,i.c,i.d,i.tx-a,
i.ty-c);g.globalAlpha=i.alpha;l.draw(g);if(this._testHit(g)){h.width=0;h.width=1;if(k)return this;else if(d)d.push(l);else return l}}}return null};m.Container=e})(window);(function(m){var e=function(a){this.initialize(a)},b=e.prototype=new Container;e._snapToPixelEnabled=false;b.autoClear=true;b.canvas=null;b.mouseX=null;b.mouseY=null;b.onMouseMove=null;b.onMouseUp=null;b.onMouseDown=null;b.snapToPixelEnabled=false;b.mouseInBounds=false;b.tickOnUpdate=true;b._activeMouseEvent=null;b._activeMouseTarget=null;b._mouseOverIntervalID=null;b._mouseOverX=0;b._mouseOverY=0;b._mouseOverTarget=null;b.Container_initialize=b.initialize;b.initialize=function(a){this.Container_initialize();
this.canvas=a;this._enableMouseEvents(true)};b.update=function(){if(this.canvas){this.autoClear&&this.clear();e._snapToPixelEnabled=this.snapToPixelEnabled;this.tickOnUpdate&&this._tick();this.draw(this.canvas.getContext("2d"),false,this.getConcatenatedMatrix(this._matrix))}};b.tick=b.update;b.clear=function(){if(this.canvas){var a=this.canvas.getContext("2d");a.setTransform(1,0,0,1,0,0);a.clearRect(0,0,this.canvas.width,this.canvas.height)}};b.toDataURL=function(a,c){c||(c="image/png");var d=this.canvas.getContext("2d"),
f=this.canvas.width,g=this.canvas.height,h;if(a){h=d.getImageData(0,0,f,g);var i=d.globalCompositeOperation;d.globalCompositeOperation="destination-over";d.fillStyle=a;d.fillRect(0,0,f,g)}var k=this.canvas.toDataURL(c);if(a){d.clearRect(0,0,f,g);d.putImageData(h,0,0);d.globalCompositeOperation=i}return k};b.enableMouseOver=function(a){if(this._mouseOverIntervalID){clearInterval(this._mouseOverIntervalID);this._mouseOverIntervalID=null}if(!(a<=0)){var c=this;this._mouseOverIntervalID=setInterval(function(){c._testMouseOver()},
1E3/Math.min(50,a));this._mouseOverX=NaN;this._mouseOverTarget=null}};b.clone=function(){var a=new e(null);this.cloneProps(a);return a};b.toString=function(){return"[Stage (name="+this.name+")]"};b._enableMouseEvents=function(){var a=this,c=m.addEventListener?m:document;c.addEventListener("mouseup",function(d){a._handleMouseUp(d)},false);c.addEventListener("mousemove",function(d){a._handleMouseMove(d)},false);c.addEventListener("dblclick",function(d){a._handleDoubleClick(d)},false);this.canvas.addEventListener("mousedown",
function(d){a._handleMouseDown(d)},false)};b._handleMouseMove=function(a){if(this.canvas){if(!a)a=m.event;var c=this.mouseInBounds;this._updateMousePosition(a.pageX,a.pageY);if(c||this.mouseInBounds){a=new MouseEvent("onMouseMove",this.mouseX,this.mouseY,this,a);if(this.onMouseMove)this.onMouseMove(a);if(this._activeMouseEvent&&this._activeMouseEvent.onMouseMove)this._activeMouseEvent.onMouseMove(a)}}else this.mouseX=this.mouseY=null};b._updateMousePosition=function(a,c){var d=this.canvas;do{a-=d.offsetLeft;
c-=d.offsetTop}while(d=d.offsetParent);if(this.mouseInBounds=a>=0&&c>=0&&a<this.canvas.width&&c<this.canvas.height){this.mouseX=a;this.mouseY=c}};b._handleMouseUp=function(a){var c=new MouseEvent("onMouseUp",this.mouseX,this.mouseY,this,a);if(this.onMouseUp)this.onMouseUp(c);if(this._activeMouseEvent&&this._activeMouseEvent.onMouseUp)this._activeMouseEvent.onMouseUp(c);if(this._activeMouseTarget&&this._activeMouseTarget.onClick&&this._getObjectsUnderPoint(this.mouseX,this.mouseY,null,true,this._mouseOverIntervalID?
3:1)==this._activeMouseTarget)this._activeMouseTarget.onClick(new MouseEvent("onClick",this.mouseX,this.mouseY,this._activeMouseTarget,a));this._activeMouseEvent=this._activeMouseTarget=null};b._handleMouseDown=function(a){if(this.onMouseDown)this.onMouseDown(new MouseEvent("onMouseDown",this.mouseX,this.mouseY,this,a));var c=this._getObjectsUnderPoint(this.mouseX,this.mouseY,null,this._mouseOverIntervalID?3:1);if(c){if(c.onPress instanceof Function){a=new MouseEvent("onPress",this.mouseX,this.mouseY,
c,a);c.onPress(a);if(a.onMouseMove||a.onMouseUp)this._activeMouseEvent=a}this._activeMouseTarget=c}};b._testMouseOver=function(){if(!(this.mouseX==this._mouseOverX&&this.mouseY==this._mouseOverY&&this.mouseInBounds)){var a=null;if(this.mouseInBounds){a=this._getObjectsUnderPoint(this.mouseX,this.mouseY,null,3);this._mouseOverX=this.mouseX;this._mouseOverY=this.mouseY}if(this._mouseOverTarget!=a){if(this._mouseOverTarget&&this._mouseOverTarget.onMouseOut)this._mouseOverTarget.onMouseOut(new MouseEvent("onMouseOut",
this.mouseX,this.mouseY,this._mouseOverTarget));if(a&&a.onMouseOver)a.onMouseOver(new MouseEvent("onMouseOver",this.mouseX,this.mouseY,a));this._mouseOverTarget=a}}};b._handleDoubleClick=function(a){if(this.onDoubleClick)this.onDoubleClick(new MouseEvent("onDoubleClick",this.mouseX,this.mouseY,this,a));var c=this._getObjectsUnderPoint(this.mouseX,this.mouseY,null,this._mouseOverIntervalID?3:1);if(c)if(c.onDoubleClick instanceof Function)c.onDoubleClick(new MouseEvent("onPress",this.mouseX,this.mouseY,
c,a))};m.Stage=e})(window);(function(m){var e=function(a){this.initialize(a)},b=e.prototype=new DisplayObject;b.image=null;b.snapToPixel=true;b.DisplayObject_initialize=b.initialize;b.initialize=function(a){this.DisplayObject_initialize();if(typeof a=="string"){this.image=new Image;this.image.src=a}else this.image=a};b.isVisible=function(){return this.visible&&this.alpha>0&&this.scaleX!=0&&this.scaleY!=0&&this.image&&(this.image.complete||this.image.getContext)};b.DisplayObject_draw=b.draw;b.draw=function(a,c){if(this.DisplayObject_draw(a,
c))return true;a.drawImage(this.image,0,0);return true};b.clone=function(){var a=new e(this.image);this.cloneProps(a);return a};b.toString=function(){return"[Bitmap (name="+this.name+")]"};m.Bitmap=e})(window);(function(m){var e=function(a){this.initialize(a)},b=e.prototype=new DisplayObject;b.onAnimationEnd=null;b.currentFrame=-1;b.currentAnimation=null;b.paused=true;b.spriteSheet=null;b.snapToPixel=true;b.offset=0;b.currentAnimationFrame=0;b._advanceCount=0;b._animation=null;b.DisplayObject_initialize=b.initialize;b.initialize=function(a){this.DisplayObject_initialize();this.spriteSheet=a};b.isVisible=function(){return this.visible&&this.alpha>0&&this.scaleX!=0&&this.scaleY!=0&&this.spriteSheet.complete&&
this.currentFrame>=0};b.DisplayObject_draw=b.draw;b.draw=function(a,c){if(this.DisplayObject_draw(a,c))return true;this._normalizeFrame();var d=this.spriteSheet.getFrameRect(this.currentFrame);if(d!=null){var f=d.rect;a.drawImage(d.image,f.x,f.y,f.width,f.height,-d.regX,-d.regY,f.width,f.height);return true}};b.gotoAndPlay=function(a){this.paused=false;this._goto(a)};b.gotoAndStop=function(a){this.paused=true;this._goto(a)};b.advance=function(){if(this._animation)this.currentAnimationFrame++;else this.currentFrame++;
this._normalizeFrame()};b.clone=function(){var a=new e(this.spriteSheet);this.cloneProps(a);return a};b.toString=function(){return"[BitmapAnimation (name="+this.name+")]"};b._tick=function(){var a=this._animation?this._animation.frequency:1;!this.paused&&(++this._advanceCount+this.offset)%a==0&&this.advance()};b._normalizeFrame=function(){var a=this._animation;if(a)if(this.currentAnimationFrame>=a.frames.length){if(a.next)this._goto(a.next);else{this.paused=true;this.currentAnimationFrame=a.frames.length-
1;this.currentFrame=a.frames[this.currentAnimationFrame]}if(this.onAnimationEnd)this.onAnimationEnd(this,a.name)}else this.currentFrame=a.frames[this.currentAnimationFrame];else if(this.currentFrame>=this.spriteSheet.getNumFrames()){this.currentFrame=0;if(this.onAnimationEnd)this.onAnimationEnd(this,null)}};b.DisplayObject_cloneProps=b.cloneProps;b.cloneProps=function(a){this.DisplayObject_cloneProps(a);a.onAnimationEnd=this.onAnimationEnd;a.currentFrame=this.currentFrame;a.currentAnimation=this.currentAnimation;
a.paused=this.paused;a.offset=this.offset;a._animation=this._animation;a.currentAnimationFrame=this.currentAnimationFrame};b._goto=function(a){if(isNaN(a)){var c=this.spriteSheet.getAnimation(a);if(c){this.currentAnimationFrame=0;this._animation=c;this.currentAnimation=a;this._normalizeFrame()}}else{this.currentAnimation=this._animation=null;this.currentFrame=a}};m.BitmapAnimation=e})(window);(function(m){var e=function(a){this.initialize(a)},b=e.prototype=new DisplayObject;b.graphics=null;b.DisplayObject_initialize=b.initialize;b.initialize=function(a){this.DisplayObject_initialize();this.graphics=a?a:new Graphics};b.isVisible=function(){return this.visible&&this.alpha>0&&this.scaleX!=0&&this.scaleY!=0&&this.graphics};b.DisplayObject_draw=b.draw;b.draw=function(a,c){if(this.DisplayObject_draw(a,c))return true;this.graphics.draw(a);return true};b.clone=function(a){a=new e(a&&this.graphics?
this.graphics.clone():this.graphics);this.cloneProps(a);return a};b.toString=function(){return"[Shape (name="+this.name+")]"};m.Shape=e})(window);(function(m){var e=function(a,c,d){this.initialize(a,c,d)},b=e.prototype=new DisplayObject;e._workingContext=document.createElement("canvas").getContext("2d");b.text="";b.font=null;b.color=null;b.textAlign=null;b.textBaseline=null;b.maxWidth=null;b.outline=false;b.lineHeight=null;b.lineWidth=null;b.DisplayObject_initialize=b.initialize;b.initialize=function(a,c,d){this.DisplayObject_initialize();this.text=a;this.font=c;this.color=d?d:"#000"};b.isVisible=function(){return Boolean(this.visible&&this.alpha>
0&&this.scaleX!=0&&this.scaleY!=0&&this.text!=null&&this.text!="")};b.DisplayObject_draw=b.draw;b.draw=function(a,c){if(this.DisplayObject_draw(a,c))return true;if(this.outline)a.strokeStyle=this.color;else a.fillStyle=this.color;a.font=this.font;a.textAlign=this.textAlign?this.textAlign:"start";a.textBaseline=this.textBaseline?this.textBaseline:"alphabetic";for(var d=String(this.text).split(/(?:\r\n|\r|\n)/),f=this.lineHeight==null?this.getMeasuredLineHeight():this.lineHeight,g=0,h=0,i=d.length;h<
i;h++){var k=a.measureText(d[h]).width;if(this.lineWidth==null||k<this.lineWidth)this._drawTextLine(a,d[h],g);else{k=d[h].split(/(\s)/);for(var j=k[0],l=1,n=k.length;l<n;l+=2)if(a.measureText(j+k[l]+k[l+1]).width>this.lineWidth){this._drawTextLine(a,j,g);g+=f;j=k[l+1]}else j+=k[l]+k[l+1];this._drawTextLine(a,j,g)}g+=f}return true};b.getMeasuredWidth=function(){return this._getWorkingContext().measureText(this.text).width};b.getMeasuredLineHeight=function(){return this._getWorkingContext().measureText("M").width*
1.2};b.clone=function(){var a=new e(this.text,this.font,this.color);this.cloneProps(a);return a};b.toString=function(){return"[Text (text="+(this.text.length>20?this.text.substr(0,17)+"...":this.text)+")]"};b.DisplayObject_cloneProps=b.cloneProps;b.cloneProps=function(a){this.DisplayObject_cloneProps(a);a.textAlign=this.textAlign;a.textBaseline=this.textBaseline;a.maxWidth=this.maxWidth;a.outline=this.outline;a.lineHeight=this.lineHeight;a.lineWidth=this.lineWidth};b._getWorkingContext=function(){var a=
e._workingContext;a.font=this.font;a.textAlign=this.textAlign?this.textAlign:"start";a.textBaseline=this.textBaseline?this.textBaseline:"alphabetic";return a};b._drawTextLine=function(a,c,d){this.outline?a.strokeText(c,0,d,this.maxWidth):a.fillText(c,0,d,this.maxWidth)};m.Text=e})(window);(function(m){var e=function(){throw"SpriteSheetUtils cannot be instantiated";};e._workingCanvas=document.createElement("canvas");e._workingContext=e._workingCanvas.getContext("2d");e.addFlippedFrames=function(b,a,c,d){if(!(!a&&!c&&!d)){var f=0;a&&e._flip(b,++f,true,false);c&&e._flip(b,++f,false,true);d&&e._flip(b,++f,true,true)}};e.extractFrame=function(b,a){if(isNaN(a))a=b.getAnimation(a).frames[0];var c=b.getFrameRect(a);if(!c)return null;var d=c.rect,f=e._workingCanvas;f.width=d.width;f.height=
d.height;e._workingContext.drawImage(c.image,d.x,d.y,d.width,d.height,0,0,d.width,d.height);c=new Image;c.src=f.toDataURL("image/png");return c};e._flip=function(b,a,c,d){for(var f=b._images,g=e._workingCanvas,h=e._workingContext,i=f.length/a,k=0;k<i;k++){var j=f[k];j.__tmp=k;g.width=j.width;g.height=j.height;h.setTransform(c?-1:1,0,0,d?-1:1,c?j.width:0,d?j.height:0);h.drawImage(j,0,0);j=new Image;j.src=g.toDataURL("image/png");f.push(j)}h=b._frames;g=h.length/a;for(k=0;k<g;k++){j=h[k];var l=j.rect.clone();
j=f[j.image.__tmp+i*a];var n={image:j,rect:l};if(c)l.x=j.width-l.x-l.width;if(d)l.y=j.height-l.y-l.height;h.push(n)}c="_"+(c?"h":"")+(d?"v":"");d=b._animations;b=b._data;f=d.length/a;for(k=0;k<f;k++){h=d[k];j=b[h];i={name:h+c,frequency:j.frequency,next:j.next,frames:[]};if(j.next)i.next+=c;h=j.frames;j=0;for(l=h.length;j<l;j++)i.frames.push(h[j]+g*a);b[i.name]=i;d.push(i.name)}};m.SpriteSheetUtils=e})(window);(function(m){var e=function(a){this.initialize(a)},b=e.prototype=new DisplayObject;b.htmlElement=null;b._style=null;b.DisplayObject_initialize=b.initialize;b.initialize=function(a){this.DisplayObject_initialize();this.mouseEnabled=false;if(this.htmlElement=a){this._style=a.style;this._style.position="absolute";this._style.transformOrigin=this._style.webkitTransformOrigin=this._style.MozTransformOrigin="0px 0px"}};b.isVisible=function(){return this.htmlElement!=null};b.draw=function(){if(this.htmlElement!=
null){var a=this._matrix,c=this.htmlElement;c.style.opacity=""+a.alpha;c.style.visibility=this.visible?"visible":"hidden";c.style.transform=c.style.webkitTransform=c.style.oTransform=["matrix("+a.a,a.b,a.c,a.d,a.tx,a.ty+")"].join(",");c.style.MozTransform=["matrix("+a.a,a.b,a.c,a.d,a.tx+"px",a.ty+"px)"].join(",");return true}};b.cache=function(){};b.uncache=function(){};b.updateCache=function(){};b.hitTest=function(){};b.localToGlobal=function(){};b.globalToLocal=function(){};b.localToLocal=function(){};
b.clone=function(){var a=new e;this.cloneProps(a);return a};b.toString=function(){return"[DOMElement (name="+this.name+")]"};b._tick=function(){if(this.htmlElement!=null)this.htmlElement.style.visibility="hidden"};m.DOMElement=e})(window);(function(m){var e=function(){this.initialize()},b=e.prototype;b.initialize=function(){};b.getBounds=function(){return new Rectangle(0,0,0,0)};b.applyFilter=function(){};b.toString=function(){return"[Filter]"};b.clone=function(){return new e};m.Filter=e})(window);(function(m){var e=function(a){this.initialize(a)},b=e.prototype=new Filter;b.matrix=null;b.initialize=function(a){this.matrix=a};b.applyFilter=function(a,c,d,f,g,h,i,k){h=h||a;k=i=null;try{var j=a.getImageData(c,d,f,g)}catch(l){return false}a=j.data;c=a.length;var n,p,q,r;n=this.matrix;d=n[0];f=n[1];g=n[2];for(var s=n[3],t=n[4],u=n[5],v=n[6],w=n[7],x=n[8],y=n[9],z=n[10],A=n[11],B=n[12],C=n[13],D=n[14],E=n[15],F=n[16],G=n[17],H=n[18],I=n[19],o=0;o<c;o+=4){n=a[o];p=a[o+1];q=a[o+2];r=a[o+3];a[o]=n*
d+p*f+q*g+r*s+t;a[o+1]=n*u+p*v+q*w+r*x+y;a[o+2]=n*z+p*A+q*B+r*C+D;a[o+3]=n*E+p*F+q*G+r*H+I}j.data=a;h.putImageData(j,i,k);return true};b.toString=function(){return"[ColorMatrixFilter]"};b.clone=function(){return new e(this.matrix)};m.ColorMatrixFilter=e})(window);
