/**
* EaselJS
* Visit http://easeljs.com/ for documentation, updates and examples.
*
* Copyright (c) 2011 Grant Skinner
* 
* Permission is hereby granted, free of charge, to any person
* obtaining a copy of this software and associated documentation
* files (the "Software"), to deal in the Software without
* restriction, including without limitation the rights to use,
* copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the
* Software is furnished to do so, subject to the following
* conditions:
* 
* The above copyright notice and this permission notice shall be
* included in all copies or substantial portions of the Software.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
* OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
* HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
* WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
* FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
**/
(function(k){UID=function(){throw"UID cannot be instantiated";};UID._nextID=0;UID.get=function(){return UID._nextID++};k.UID=UID})(window);(function(k){Ticker=function(){throw"Ticker cannot be instantiated.";};Ticker._listeners=[];Ticker._pauseable=[];Ticker._paused=!1;Ticker._inited=!1;Ticker._startTime=0;Ticker._pausedTime=0;Ticker._ticks=0;Ticker._pausedTickers=0;Ticker._interval=50;Ticker._intervalID=null;Ticker._lastTime=0;Ticker._times=[];Ticker.addListener=function(b,a){if(!Ticker._inited)Ticker._inited=!0,Ticker.setInterval(Ticker._interval);this.removeListener(b);Ticker._pauseable[Ticker._listeners.length]=a==null?!0:a;Ticker._listeners.push(b)};
Ticker.removeListener=function(b){Ticker._listeners!=null&&(b=Ticker._listeners.indexOf(b),b!=-1&&(Ticker._listeners.splice(b,1),Ticker._pauseable.splice(b,1)))};Ticker.removeAllListeners=function(){Ticker._listeners=[];Ticker._pauseable=[]};Ticker.setInterval=function(b){Ticker._intervalID!=null&&clearInterval(Ticker._intervalID);Ticker._lastTime=Ticker._getTime();Ticker._interval=b;Ticker._intervalID=setInterval(Ticker._tick,b)};Ticker.getInterval=function(){return Ticker._interval};Ticker.getFPS=
function(){return 1E3/Ticker._interval};Ticker.setFPS=function(b){Ticker.setInterval(1E3/b)};Ticker.getMeasuredFPS=function(b){if(Ticker._times.length<2)return-1;b==null&&(b=Ticker.getFPS()>>1);b=Math.min(Ticker._times.length-1,b);return 1E3/((Ticker._times[0]-Ticker._times[b])/b)};Ticker.setPaused=function(b){Ticker._paused=b};Ticker.getPaused=function(){return Ticker._paused};Ticker.getTime=function(b){return Ticker._getTime()-Ticker._startTime-(b?Ticker._pausedTime:0)};Ticker.getTicks=function(b){return Ticker._ticks-
(b?Ticker._pausedTickers:0)};Ticker._tick=function(){Ticker._ticks++;var b=Ticker.getTime(!1),a=b-Ticker._lastTime,o=Ticker._paused;o&&(Ticker._pausedTickers++,Ticker._pausedTime+=a);Ticker._lastTime=b;for(var c=Ticker._pauseable,d=Ticker._listeners,e=d?d.length:0,f=0;f<e;f++){var g=c[f],h=d[f];h==null||o&&g||h.tick==null||h.tick(a)}Ticker._times.unshift(b);Ticker._times.length>100&&Ticker._times.pop()};Ticker._getTime=function(){return(new Date).getTime()};Ticker._startTime=Ticker._getTime();k.Ticker=
Ticker})(window);(function(k){EaselMouseEvent=function(a,o,b){this.initialize(a,o,b)};var b=EaselMouseEvent.prototype;b.stageX=0;b.stageY=0;b.type=null;b.nativeEvent=null;b.onMouseMove=null;b.onMouseUp=null;b.initialize=function(a,o,b){this.type=a;this.stageX=o;this.stageY=b};b.clone=function(){var a=new EaselMouseEvent(this.type,this.stageX,this.stageY);a.nativeEvent=this.nativeEvent;return a};b.toString=function(){return"[EaselMouseEvent (type="+this.type+" stageX="+this.stageX+" stageY="+this.stageY+")]"};k.EaselMouseEvent=
EaselMouseEvent})(window);(function(k){Matrix2D=function(a,o,b,d,e,f){this.initialize(a,o,b,d,e,f)};var b=Matrix2D.prototype;Matrix2D.identity=null;Matrix2D.DEG_TO_RAD=Math.PI/180;b.a=1;b.b=0;b.c=0;b.d=1;b.tx=0;b.ty=0;b.alpha=1;b.shadow=null;b.compositeOperation=null;b.initialize=function(a,b,c,d,e,f){if(a!=null)this.a=a;if(b!=null)this.b=b;if(c!=null)this.c=c;if(d!=null)this.d=d;if(e!=null)this.tx=e;if(f!=null)this.ty=f};b.prepend=function(a,b,c,d,e,f){var g=this.tx;if(a!=1||b!=0||c!=0||d!=1){var h=this.a,i=this.c;this.a=
h*a+this.b*c;this.b=h*b+this.b*d;this.c=i*a+this.d*c;this.d=i*b+this.d*d}this.tx=g*a+this.ty*c+e;this.ty=g*b+this.ty*d+f};b.append=function(a,b,c,d,e,f){var g=this.a,h=this.b,i=this.c,j=this.d;this.a=a*g+b*i;this.b=a*h+b*j;this.c=c*g+d*i;this.d=c*h+d*j;this.tx=e*g+f*i+this.tx;this.ty=e*h+f*j+this.ty};b.prependMatrix=function(a){this.prepend(a.a,a.b,a.c,a.d,a.tx,a.ty);this.prependProperties(a.alpha,a.shadow,a.compositeOperation)};b.appendMatrix=function(a){this.append(a.a,a.b,a.c,a.d,a.tx,a.ty);this.appendProperties(a.alpha,
a.shadow,a.compositeOperation)};b.prependTransform=function(a,b,c,d,e,f,g,h,i){if(e%360){var j=e*Matrix2D.DEG_TO_RAD;e=Math.cos(j);j=Math.sin(j)}else e=1,j=0;if(h||i)this.tx-=h,this.ty-=i;f||g?(f*=Matrix2D.DEG_TO_RAD,g*=Matrix2D.DEG_TO_RAD,this.prepend(e*c,j*c,-j*d,e*d,0,0),this.prepend(Math.cos(g),Math.sin(g),-Math.sin(f),Math.cos(f),a,b)):this.prepend(e*c,j*c,-j*d,e*d,a,b)};b.appendTransform=function(a,b,c,d,e,f,g,h,i){if(e%360){var j=e*Matrix2D.DEG_TO_RAD;e=Math.cos(j);j=Math.sin(j)}else e=1,j=
0;f||g?(f*=Matrix2D.DEG_TO_RAD,g*=Matrix2D.DEG_TO_RAD,this.append(Math.cos(g),Math.sin(g),-Math.sin(f),Math.cos(f),a,b),this.append(e*c,j*c,-j*d,e*d,0,0)):this.append(e*c,j*c,-j*d,e*d,a,b);if(h||i)this.tx-=h*this.a+i*this.c,this.ty-=h*this.b+i*this.d};b.rotate=function(a){var b=Math.cos(a);a=Math.sin(a);var c=this.a,d=this.c,e=this.tx;this.a=c*b-this.b*a;this.b=c*a+this.b*b;this.c=d*b-this.d*a;this.d=d*a+this.d*b;this.tx=e*b-this.ty*a;this.ty=e*a+this.ty*b};b.skew=function(a,b){a*=Matrix2D.DEG_TO_RAD;
b*=Matrix2D.DEG_TO_RAD;this.append(Math.cos(b),Math.sin(b),-Math.sin(a),Math.cos(a),0,0)};b.scale=function(a,b){this.a*=a;this.d*=b;this.tx*=a;this.ty*=b};b.translate=function(a,b){this.tx+=a;this.ty+=b};b.identity=function(){this.alpha=this.a=this.d=1;this.b=this.c=this.tx=this.ty=0;this.shadow=this.compositeOperation=null};b.invert=function(){var a=this.a,b=this.b,c=this.c,d=this.d,e=this.tx,f=a*d-b*c;this.a=d/f;this.b=-b/f;this.c=-c/f;this.d=a/f;this.tx=(c*this.ty-d*e)/f;this.ty=-(a*this.ty-b*
e)/f};b.decompose=function(a){a==null&&(a={});a.x=this.tx;a.y=this.ty;a.scaleX=Math.sqrt(this.a*this.a+this.b*this.b);a.scaleY=Math.sqrt(this.c*this.c+this.d*this.d);var b=Math.atan2(-this.c,this.d),c=Math.atan2(this.b,this.a);b==c?(a.rotation=c/Matrix2D.DEG_TO_RAD,this.a<0&&this.d>=0&&(a.rotation+=a.rotation<=0?180:-180),a.skewX=a.skewY=0):(a.skewX=b/Matrix2D.DEG_TO_RAD,a.skewY=c/Matrix2D.DEG_TO_RAD);return a};b.appendProperties=function(a,b,c){this.alpha*=a;this.shadow=b||this.shadow;this.compositeOperation=
c||this.compositeOperation};b.prependProperties=function(a,b,c){this.alpha*=a;this.shadow=this.shadow||b;this.compositeOperation=this.compositeOperation||c};b.clone=function(){var a=new Matrix2D(this.a,this.b,this.c,this.d,this.tx,this.ty);a.shadow=this.shadow;a.alpha=this.alpha;a.compositeOperation=this.compositeOperation;return a};b.toString=function(){return"[Matrix2D (a="+this.a+" b="+this.b+" c="+this.c+" d="+this.d+" tx="+this.tx+" ty="+this.ty+")]"};Matrix2D.identity=new Matrix2D(1,0,0,1,0,
0);k.Matrix2D=Matrix2D})(window);(function(k){Point=function(a,b){this.initialize(a,b)};var b=Point.prototype;b.x=0;b.y=0;b.initialize=function(a,b){this.x=a==null?0:a;this.y=b==null?0:b};b.clone=function(){return new Point(this.x,this.y)};b.toString=function(){return"[Point (x="+this.x+" y="+this.y+")]"};k.Point=Point})(window);(function(k){Rectangle=function(a,b,c,d){this.initialize(a,b,c,d)};var b=Rectangle.prototype;b.x=0;b.y=0;b.width=0;b.height=0;b.initialize=function(a,b,c,d){this.x=a==null?0:a;this.y=b==null?0:b;this.width=c==null?0:c;this.height=d==null?0:d};b.clone=function(){return new Rectangle(this.x,this.y,this.width,this.height)};b.toString=function(){return"[Rectangle (x="+this.x+" y="+this.y+" width="+this.width+" height="+this.height+")]"};k.Rectangle=Rectangle})(window);(function(k){Shadow=function(a,b,c,d){this.initialize(a,b,c,d)};var b=Shadow.prototype;Shadow.identity=null;b.color=null;b.offsetX=0;b.offsetY=0;b.blur=0;b.initialize=function(a,b,c,d){this.color=a;this.offsetX=b;this.offsetY=c;this.blur=d};b.toString=function(){return"[Shadow]"};b.clone=function(){return new Shadow(this.color,this.offsetX,this.offsetY,this.blur)};Shadow.identity=new Shadow(null,0,0,0);k.Shadow=Shadow})(window);(function(k){SpriteSheet=function(a,b,c,d){this.initialize(a,b,c,d)};var b=SpriteSheet.prototype;b.image=null;b.frameWidth=0;b.frameHeight=0;b.frameData=null;b.loop=!0;b.totalFrames=0;b.initialize=function(a,b,c,d){this.image=a;this.frameWidth=b;this.frameHeight=c;this.frameData=d};b.toString=function(){return"[SpriteSheet]"};b.clone=function(){var a=new SpriteSheet(this.image,this.frameWidth,this.frameHeight,this.frameData);a.loop=this.loop;a.totalFrames=this.totalFrames;return a};k.SpriteSheet=
SpriteSheet})(window);(function(k){function b(a,b){this.f=a;this.params=b}b.prototype.exec=function(a){this.f.apply(a,this.params)};Graphics=function(a){this.initialize(a)};var a=Graphics.prototype;Graphics.getRGB=function(a,b,d,e){a!=null&&d==null&&(e=b,d=a&255,b=a>>8&255,a=a>>16&255);return e==null?"rgb("+a+","+b+","+d+")":"rgba("+a+","+b+","+d+","+e+")"};Graphics.getHSL=function(a,b,d,e){return e==null?"hsl("+a%360+","+b+"%,"+d+"%)":"hsla("+a%360+","+b+"%,"+d+"%,"+e+")"};Graphics.STROKE_CAPS_MAP=["butt","round","square"];
Graphics.STROKE_JOINTS_MAP=["miter","round","bevel"];Graphics._ctx=document.createElement("canvas").getContext("2d");Graphics.beginCmd=new b(Graphics._ctx.beginPath,[]);Graphics.fillCmd=new b(Graphics._ctx.fill,[]);Graphics.strokeCmd=new b(Graphics._ctx.stroke,[]);a._strokeInstructions=null;a._strokeStyleInstructions=null;a._fillInstructions=null;a._instructions=null;a._oldInstructions=null;a._activeInstructions=null;a._active=!1;a._dirty=!1;a._minX=NaN;a._minY=NaN;a._maxX=NaN;a._maxY=NaN;a._boundsQueue=
null;a._x=0;a._y=0;a.initialize=function(a){this.clear();this._ctx=Graphics._ctx;with(this)eval(a)};a.draw=function(a){this._dirty&&this._updateInstructions();for(var b=this._instructions,d=0,e=b.length;d<e;d++)b[d].exec(a)};a.getBounds=function(){this._boundsQueue.length&&this._updateBounds();return isNaN(this._minX)?null:new Rectangle(this._minX,this._minY,this._maxX-this._minX,this._maxY-this._minY)};a.moveTo=function(a,c){this._activeInstructions.push(new b(this._ctx.moveTo,[a,c]));return this};
a.lineTo=function(a,c){this._dirty=this._active=!0;this._activeInstructions.push(new b(this._ctx.lineTo,[a,c]));return this};a.arcTo=function(a,c,d,e,f){this._dirty=this._active=!0;this._activeInstructions.push(new b(this._ctx.arcTo,[a,c,d,e,f]));return this};a.arc=function(a,c,d,e,f,g){this._dirty=this._active=!0;g==null&&(g=!1);this._activeInstructions.push(new b(this._ctx.arc,[a,c,d,e,f,g]));return this};a.quadraticCurveTo=function(a,c,d,e){this._dirty=this._active=!0;this._activeInstructions.push(new b(this._ctx.quadraticCurveTo,
[a,c,d,e]));return this};a.bezierCurveTo=function(a,c,d,e,f,g){this._dirty=this._active=!0;this._activeInstructions.push(new b(this._ctx.bezierCurveTo,[a,c,d,e,f,g]));this._boundsQueue.push(new b(this._bezierCurveToBounds,[_x,_y,a,c,d,e,f,g]));return this};a.rect=function(a,c,d,e){this._dirty=this._active=!0;this._activeInstructions.push(new b(this._ctx.rect,[a,c,d-1,e]));return this};a.closePath=function(){if(this._active)this._dirty=!0,this._activeInstructions.push(new b(this._ctx.closePath,[]));
return this};a.clear=function(){this._instructions=[];this._oldInstructions=[];this._activeInstructions=[];this._strokeStyleInstructions=this._strokeInstructions=this._fillInstructions=null;this._active=this._dirty=!1;this._boundsQueue=[];this._minX=this._minY=this._maxX=this._maxY=NaN;return this};a.beginFill=function(a){this._active&&this._newPath();this._fillInstructions=a?[new b(this._setProp,["fillStyle",a])]:null;return this};a.beginLinearGradientFill=function(a,c,d,e,f,g){this._active&&this._newPath();
d=this._ctx.createLinearGradient(d,e,f,g);e=0;for(f=a.length;e<f;e++)d.addColorStop(c[e],a[e]);this._fillInstructions=[new b(this._setProp,["fillStyle",d])];return this};a.beginRadialGradientFill=function(a,c,d,e,f,g,h,i){this._active&&this._newPath();d=this._ctx.createRadialGradient(d,e,f,g,h,i);e=0;for(f=a.length;e<f;e++)d.addColorStop(c[e],a[e]);this._fillInstructions=[new b(this._setProp,["fillStyle",d])];return this};a.beginBitmapFill=function(a,c){this._active&&this._newPath();var d=this._ctx.createPattern(a,
c||"");this._fillInstructions=[new b(this._setProp,["fillStyle",d])];return this};a.endFill=function(){this.beginFill(null);return this};a.setStrokeStyle=function(a,c,d,e){this._active&&this._newPath();this._strokeStyleInstructions=[new b(this._setProp,["lineWidth",a==null?"1":a]),new b(this._setProp,["lineCap",c==null?"butt":isNaN(c)?c:Graphics.STROKE_CAPS_MAP[c]]),new b(this._setProp,["lineJoin",d==null?"miter":isNaN(d)?d:Graphics.STROKE_JOINTS_MAP[d]]),new b(this._setProp,["miterLimit",e==null?
"10":e])];return this};a.beginStroke=function(a){this._active&&this._newPath();this._strokeInstructions=a?[new b(this._setProp,["strokeStyle",a])]:null;return this};a.beginLinearGradientStroke=function(a,c,d,e,f,g){this._active&&this._newPath();d=this._ctx.createLinearGradient(d,e,f,g);e=0;for(f=a.length;e<f;e++)d.addColorStop(c[e],a[e]);this._strokeInstructions=[new b(this._setProp,["strokeStyle",d])];return this};a.beginRadialGradientStroke=function(a,c,d,e,f,g,h,i){this._active&&this._newPath();
d=this._ctx.createRadialGradient(d,e,f,g,h,i);e=0;for(f=a.length;e<f;e++)d.addColorStop(c[e],a[e]);this._strokeInstructions=[new b(this._setProp,["strokeStyle",d])];return this};a.beginBitmapStroke=function(a,c){this._active&&this._newPath();var d=this._ctx.createPattern(a,c||"");this._strokeInstructions=[new b(this._setProp,["strokeStyle",d])];return this};a.endStroke=function(){this.beginStroke(null);return this};a.curveTo=a.quadraticCurveTo;a.drawRect=a.rect;a.drawRoundRect=function(a,b,d,e,f){this.drawRoundRectComplex(a,
b,d,e,f,f,f,f);return this};a.drawRoundRectComplex=function(a,c,d,e,f,g,h,i){this._dirty=this._active=!0;this._activeInstructions.push(new b(this._ctx.moveTo,[a+f,c]),new b(this._ctx.lineTo,[a+d-g,c]),new b(this._ctx.arc,[a+d-g,c+g,g,-Math.PI/2,0,!1]),new b(this._ctx.lineTo,[a+d,c+e-h]),new b(this._ctx.arc,[a+d-h,c+e-h,h,0,Math.PI/2,!1]),new b(this._ctx.lineTo,[a+i,c+e]),new b(this._ctx.arc,[a+i,c+e-i,i,Math.PI/2,Math.PI,!1]),new b(this._ctx.lineTo,[a,c+f]),new b(this._ctx.arc,[a+f,c+f,f,Math.PI,
Math.PI*3/2,!1]));return this};a.drawCircle=function(a,b,d){this.arc(a,b,d,0,Math.PI*2);return this};a.drawEllipse=function(a,c,d,e){this._dirty=this._active=!0;var f=d/2*0.5522848,g=e/2*0.5522848,h=a+d,i=c+e;d=a+d/2;e=c+e/2;this._activeInstructions.push(new b(this._ctx.moveTo,[a,e]),new b(this._ctx.bezierCurveTo,[a,e-g,d-f,c,d,c]),new b(this._ctx.bezierCurveTo,[d+f,c,h,e-g,h,e]),new b(this._ctx.bezierCurveTo,[h,e+g,d+f,i,d,i]),new b(this._ctx.bezierCurveTo,[d-f,i,a,e+g,a,e]));return this};a.drawPolyStar=
function(a,c,d,e,f,g){this._dirty=this._active=!0;f==null&&(f=0);f=1-f;g==null?g=0:g/=180/Math.PI;var h=Math.PI/e;this._activeInstructions.push(new b(this._ctx.moveTo,[a+Math.cos(g)*d,c+Math.sin(g)*d]));for(var i=0;i<e;i++)g+=h,f!=1&&this._activeInstructions.push(new b(this._ctx.lineTo,[a+Math.cos(g)*d*f,c+Math.sin(g)*d*f])),g+=h,this._activeInstructions.push(new b(this._ctx.lineTo,[a+Math.cos(g)*d,c+Math.sin(g)*d]));return this};a.clone=function(){var a=new Graphics;a._instructions=this._instructions.slice();
a._activeInstructions=this._activeInstructions.slice();a._oldInstructions=this._oldInstructions.slice();if(this._fillInstructions)a._fillInstructions=this._fillInstructions.slice();if(this._strokeInstructions)a._strokeInstructions=this._strokeInstructions.slice();if(this._strokeStyleInstructions)a._strokeStyleInstructions=this._strokeStyleInstructions.slice();a._active=this._active;a._dirty=this._dirty;return a};a.toString=function(){return"[Graphics]"};a.mt=a.moveTo;a.lt=a.lineTo;a.at=a.arcTo;a.bt=
a.bezierCurveTo;a.qt=a.quadraticCurveTo;a.a=a.arc;a.r=a.rect;a.cp=a.closePath;a.c=a.clear;a.f=a.beginFill;a.lf=a.beginLinearGradientFill;a.rf=a.beginRadialGradientFill;a.bf=a.beginBitmapFill;a.ef=a.endFill;a.ss=a.setStrokeStyle;a.s=a.beginStroke;a.ls=a.beginLinearGradientStroke;a.rs=a.beginRadialGradientStroke;a.bs=a.beginBitmapStroke;a.es=a.endStroke;a.dr=a.drawRect;a.rr=a.drawRoundRect;a.rc=a.drawRoundRectComplex;a.dc=a.drawCircle;a.de=a.drawEllipse;a.dp=a.drawPolyStar;a._updateInstructions=function(){this._instructions=
this._oldInstructions.slice();this._instructions.push(Graphics.beginCmd);this._fillInstructions&&this._instructions.push.apply(this._instructions,this._fillInstructions);this._strokeInstructions&&(this._instructions.push.apply(this._instructions,this._strokeInstructions),this._strokeStyleInstructions&&this._instructions.push.apply(this._instructions,this._strokeStyleInstructions));this._instructions.push.apply(this._instructions,this._activeInstructions);this._fillInstructions&&this._instructions.push(Graphics.fillCmd);
this._strokeInstructions&&this._instructions.push(Graphics.strokeCmd)};a._newPath=function(){this._dirty&&this._updateInstructions();this._oldInstructions=this._instructions;this._activeInstructions=[];this._active=this._dirty=!1};a._setProp=function(a,b){this[a]=b};a._extendBounds=function(a,b){if(isNaN(this._minX))this._minX=this._maxX=a,this._minY=this._maxY=b;else{if(a<this._minX)this._minX=a;else if(a>this._maxX)this._maxX=a;if(b<this._minY)this._minY=b;else if(b>this._maxY)this._maxY=b}};a._updateBounds=
function(){for(;boundsQueue.length;)boundsQueue.pop().exec(this)};a._bezierCurveBounds=function(){};k.Graphics=Graphics})(window);(function(k){DisplayObject=function(){this.initialize()};var b=DisplayObject.prototype;DisplayObject.suppressCrossDomainErrors=!1;DisplayObject._hitTestCanvas=document.createElement("canvas");DisplayObject._hitTestCanvas.width=DisplayObject._hitTestCanvas.height=1;DisplayObject._hitTestContext=DisplayObject._hitTestCanvas.getContext("2d");DisplayObject._workingMatrix=new Matrix2D;b.alpha=1;b.cacheCanvas=null;b.id=-1;b.mouseEnabled=!0;b.name=null;b.parent=null;b.regX=0;b.regY=0;b.rotation=0;b.scaleX=
1;b.scaleY=1;b.skewX=0;b.skewY=0;b.shadow=null;b.visible=!0;b.x=0;b.y=0;b.compositeOperation=null;b.snapToPixel=!1;b.onPress=null;b.onClick=null;b.onDoubleClick=null;b.onMouseOver=null;b.onMouseOut=null;b.filters=null;b._cacheOffsetX=0;b._cacheOffsetY=0;b._cacheDraw=!1;b._activeContext=null;b._restoreContext=!1;b._revertShadow=!1;b._revertX=0;b._revertY=0;b._revertAlpha=1;b._minX=NaN;b._minY=NaN;b._maxX=NaN;b._maxY=NaN;b.initialize=function(){this.id=UID.get();this.children=[]};b.isVisible=function(){return this.visible&&
this.alpha>0&&this.scaleX!=0&&this.scaleY!=0};b.draw=function(a,b){if(b||!this.cacheCanvas)return!1;a.translate(this._cacheOffsetX,this._cacheOffsetY);a.drawImage(this.cacheCanvas,0,0);a.translate(-this._cacheOffsetX,-this._cacheOffsetY);return!0};b.cache=function(a,b,c,d){var e;if(this.cacheCanvas==null)this.cacheCanvas=document.createElement("canvas");e=this.cacheCanvas.getContext("2d");this.cacheCanvas.width=c;this.cacheCanvas.height=d;e.setTransform(1,0,0,1,-a,-b);e.clearRect(0,0,c+1,d+1);this.draw(e,
!0);this._cacheOffsetX=a;this._cacheOffsetY=b;this._applyFilters()};b.updateCache=function(a){if(this.cacheCanvas==null)throw"cache() must be called before updateCache()";var b=this.cacheCanvas.getContext("2d");b.setTransform(1,0,0,1,-this._cacheOffsetX,-this._cacheOffsetY);a?b.globalCompositeOperation=a:b.clearRect(0,0,this.cacheCanvas.width+1,this.cacheCanvas.height+1);this.draw(b,!0);if(a)b.globalCompositeOperation="source-over";this._applyFilters()};b.uncache=function(){this.cacheCanvas=null;
this.cacheOffsetX=this.cacheOffsetY=0};b.getStage=function(){for(var a=this;a.parent;)a=a.parent;if(a instanceof Stage)return a;return null};b.localToGlobal=function(a,b){var c=this.getConcatenatedMatrix();if(c==null)return null;c.append(1,0,0,1,a,b);return new Point(c.tx,c.ty)};b.globalToLocal=function(a,b){var c=this.getConcatenatedMatrix();if(c==null)return null;c.invert();c.append(1,0,0,1,a,b);return new Point(c.tx,c.ty)};b.localToLocal=function(a,b,c){a=this.localToGlobal(a,b);return c.globalToLocal(a.x,
a.y)};b.setTransform=function(a,b,c,d,e,f,g,h,i){this.x=a||0;this.y=b||0;this.scaleX=c==null?1:c;this.scaleY=d==null?1:d;this.rotation=e||0;this.skewX=f||0;this.skewY=g||0;this.regX=h||0;this.regY=i||0};b.getConcatenatedMatrix=function(a){a?a.identity():a=new Matrix2D;for(var b=this;b!=null;)a.prependTransform(b.x,b.y,b.scaleX,b.scaleY,b.rotation,b.skewX,b.skewY,b.regX,b.regY),a.prependProperties(b.alpha,b.shadow,b.compositeOperation),b=b.parent;return a};b.hitTest=function(a,b){var c=DisplayObject._hitTestContext,
d=DisplayObject._hitTestCanvas;c.setTransform(1,0,0,1,-a,-b);this.draw(c);c=this._testHit(c);d.width=0;d.width=1;return c};b.getBounds=function(){return isNaN(this._minX)?null:new Rectangle(this._minX,this._minY,this._maxX-this._minX,this._maxY-this._minY)};b.clone=function(){var a=new DisplayObject;this.cloneProps(a);return a};b.toString=function(){return"[DisplayObject (name="+this.name+")]"};b.cloneProps=function(a){a.alpha=this.alpha;a.name=this.name;a.regX=this.regX;a.regY=this.regY;a.rotation=
this.rotation;a.scaleX=this.scaleX;a.scaleY=this.scaleY;a.shadow=this.shadow;a.skewX=this.skewX;a.skewY=this.skewY;a.visible=this.visible;a.x=this.x;a.y=this.y;a.mouseEnabled=this.mouseEnabled;a.compositeOperation=this.compositeOperation};b.applyShadow=function(a,b){b=b||Shadow.identity;a.shadowColor=b.color;a.shadowOffsetX=b.offsetX;a.shadowOffsetY=b.offsetY;a.shadowBlur=b.blur};b._testHit=function(a){try{var b=a.getImageData(0,0,1,1).data[3]>1}catch(c){if(!DisplayObject.suppressCrossDomainErrors)throw"An error has occured. This is most likely due to security restrictions on reading canvas pixel data with local or cross-domain images.";
}return b};b._extendBounds=function(a,b){if(isNaN(this._minX))this._minX=this._maxX=a,this._minY=this._maxY=b;else{if(a<this._minX)this._minX=a;else if(a>this._maxX)this._maxX=a;if(b<this._minY)this._minY=b;else if(b>this._maxY)this._maxY=b}};b._applyFilters=function(){if(this.filters&&this.filters.length!=0&&this.cacheCanvas)for(var a=this.filters.length,b=this.cacheCanvas.getContext("2d"),c=this.cacheCanvas.width,d=this.cacheCanvas.height,e=0;e<a;e++)this.filters[e].applyFilter(b,0,0,c,d)};k.DisplayObject=
DisplayObject})(window);(function(k){Container=function(){this.initialize()};var b=Container.prototype=new DisplayObject;b.children=null;b.DisplayObject_initialize=b.initialize;b.initialize=function(){this.DisplayObject_initialize();this.children=[]};b.isVisible=function(){return this.visible&&this.alpha>0&&this.children.length&&this.scaleX!=0&&this.scaleY!=0};b.DisplayObject_draw=b.draw;b.draw=function(a,b,c){var d=Stage._snapToPixelEnabled;c||(c=new Matrix2D,c.appendProperties(this.alpha,this.shadow,this.compositeOperation));
if(this.DisplayObject_draw(a,b))return!0;b=this.children.length;for(var e=this.children.slice(0),f=0;f<b;f++){var g=e[f];g.tick&&g.tick();if(g.isVisible()){var h=!1,i=c.clone();i.appendTransform(g.x,g.y,g.scaleX,g.scaleY,g.rotation,g.skewX,g.skewY,g.regX,g.regY);i.appendProperties(g.alpha,g.shadow,g.compositeOperation);if(!(g instanceof Container))d&&g.snapToPixel&&i.a==1&&i.b==0&&i.c==0&&i.d==1?a.setTransform(i.a,i.b,i.c,i.d,i.tx+0.5|0,i.ty+0.5|0):a.setTransform(i.a,i.b,i.c,i.d,i.tx,i.ty),a.globalAlpha=
i.alpha,a.globalCompositeOperation=i.compositeOperation||"source-over",(h=i.shadow)&&this.applyShadow(a,h);g.draw(a,!1,i);h&&this.applyShadow(a)}}return!0};b.addChild=function(a){var b=arguments.length;if(b>1){for(var c=0;c<b;c++)this.addChild(arguments[c]);return arguments[b-1]}a.parent&&a.parent.removeChild(a);a.parent=this;this.children.push(a);return a};b.addChildAt=function(a,b){var c=arguments.length;if(c>2){b=arguments[d-1];for(var d=0;d<c-1;d++)this.addChildAt(arguments[d],b+d);return arguments[c-
2]}a.parent&&a.parent.removeChild(a);a.parent=this;this.children.splice(b,0,a);return a};b.removeChild=function(a){var b=arguments.length;if(b>1){for(var c=!0,d=0;d<b;d++)c=c&&this.removeChild(arguments[d]);return c}return this.removeChildAt(this.children.indexOf(a))};b.removeChildAt=function(a){var b=arguments.length;if(b>1){for(var c=[],d=0;d<b;d++)c[d]=arguments[d];c.sort(function(a,b){return b-a});var e=!0;for(d=0;d<b;d++)e=e&&this.removeChildAt(c[d]);return e}if(a<0||a>this.children.length-1)return!1;
b=this.children[a];if(b!=null)b.parent=null;this.children.splice(a,1);return!0};b.removeAllChildren=function(){for(;this.children.length;)this.removeChildAt(0)};b.getChildAt=function(a){return this.children[a]};b.sortChildren=function(a){this.children.sort(a)};b.getChildIndex=function(a){return this.children.indexOf(a)};b.getNumChildren=function(){return this.children.length};b.contains=function(a){for(;a;){if(a==this)return!0;a=a.parent}return!1};b.hitTest=function(a,b){return this.getObjectUnderPoint(a,
b)!=null};b.getObjectsUnderPoint=function(a,b){var c=[],d=this.localToGlobal(a,b);this._getObjectsUnderPoint(d.x,d.y,c);return c};b.getObjectUnderPoint=function(a,b){var c=this.localToGlobal(a,b);return this._getObjectsUnderPoint(c.x,c.y)};b.clone=function(a){var b=new Container;this.cloneProps(b);if(a)for(var c=b.children=[],d=0,e=this.children.length;d<e;d++)c.push(this.children[d].clone(a));return b};b.toString=function(){return"[Container (name="+this.name+")]"};b._getObjectsUnderPoint=function(a,
b,c,d){var e=DisplayObject._hitTestContext,f=DisplayObject._hitTestCanvas,g=DisplayObject._workingMatrix,h=d&1&&(this.onPress||this.onClick||this.onDoubleClick)||d&2&&(this.onMouseOver||this.onMouseOut);if(this.cacheCanvas)if(this.getConcatenatedMatrix(g),e.setTransform(g.a,g.b,g.c,g.d,g.tx-a,g.ty-b),e.globalAlpha=g.alpha,this.draw(e),this._testHit(e)){if(f.width=0,f.width=1,h)return this}else return null;for(var i=this.children.length-1;i>=0;i--){var j=this.children[i];if(j.isVisible()&&j.mouseEnabled)if(j instanceof
Container)if(h){if(j=j._getObjectsUnderPoint(a,b))return this}else{if(j=j._getObjectsUnderPoint(a,b,c,d),!c&&j)return j}else if(!d||h||d&1&&(j.onPress||j.onClick||j.onDoubleClick)||d&2&&(j.onMouseOver||j.onMouseOut))if(j.getConcatenatedMatrix(g),e.setTransform(g.a,g.b,g.c,g.d,g.tx-a,g.ty-b),e.globalAlpha=g.alpha,j.draw(e),this._testHit(e))if(f.width=0,f.width=1,h)return this;else if(c)c.push(j);else return j}return null};k.Container=Container})(window);(function(k){Stage=function(a){this.initialize(a)};var b=Stage.prototype=new Container;Stage._snapToPixelEnabled=!1;b.autoClear=!0;b.canvas=null;b.mouseX=null;b.mouseY=null;b.onMouseMove=null;b.onMouseUp=null;b.onMouseDown=null;b.snapToPixelEnabled=!1;b.mouseInBounds=!1;b._tmpCanvas=null;b._activeEaselMouseEvent=null;b._activeMouseTarget=null;b._mouseOverIntervalID=null;b._mouseOverX=0;b._mouseOverY=0;b._mouseOverTarget=null;b.Container_initialize=b.initialize;b.initialize=function(a){this.Container_initialize();
this.canvas=a;this.mouseChildren=!0;var b=this;k.addEventListener?(k.addEventListener("mouseup",function(a){b._handleMouseUp(a)},!1),k.addEventListener("mousemove",function(a){b._handleMouseMove(a)},!1),k.addEventListener("dblclick",function(a){b._handleDoubleClick(a)},!1)):document.addEventListener&&(document.addEventListener("mouseup",function(a){b._handleMouseUp(a)},!1),document.addEventListener("mousemove",function(a){b._handleMouseMove(a)},!1),document.addEventListener("dblclick",function(a){b._handleDoubleClick(a)},
!1));a.addEventListener("mousedown",function(a){b._handleMouseDown(a)},!1)};b.update=function(){if(this.canvas)this.autoClear&&this.clear(),Stage._snapToPixelEnabled=this.snapToPixelEnabled,this.draw(this.canvas.getContext("2d"),!1,this.getConcatenatedMatrix(DisplayObject._workingMatrix))};b.tick=b.update;b.clear=function(){if(this.canvas){var a=this.canvas.getContext("2d");a.setTransform(1,0,0,1,0,0);a.clearRect(0,0,this.canvas.width,this.canvas.height)}};b.toDataURL=function(a,b){b||(b="image/png");
var c=this.canvas.getContext("2d"),d=this.canvas.width,e=this.canvas.height,f;if(a){f=c.getImageData(0,0,d,e);var g=c.globalCompositeOperation;c.globalCompositeOperation="destination-over";c.fillStyle=a;c.fillRect(0,0,d,e)}var h=this.canvas.toDataURL(b);if(a)c.clearRect(0,0,d,e),c.putImageData(f,0,0),c.globalCompositeOperation=g;return h};b.enableMouseOver=function(a){if(this._mouseOverIntervalID)clearInterval(this._mouseOverIntervalID),this._mouseOverIntervalID=null;if(!(a<=0)){var b=this;this._mouseOverIntervalID=
setInterval(function(){b._testMouseOver()},1E3/Math.min(50,a));this._mouseOverX=NaN;this._mouseOverTarget=null}};b.clone=function(){var a=new Stage(null);this.cloneProps(a);return a};b.toString=function(){return"[Stage (name="+this.name+")]"};b._handleMouseMove=function(a){if(this.canvas){if(!a)a=k.event;var b=this.mouseInBounds;this._updateMousePosition(a.pageX,a.pageY);if(b||this.mouseInBounds){b=new EaselMouseEvent("onMouseMove",this.mouseX,this.mouseY);b.nativeEvent=a;if(this.onMouseMove)this.onMouseMove(b);
if(this._activeEaselMouseEvent&&this._activeEaselMouseEvent.onMouseMove)this._activeEaselMouseEvent.onMouseMove(b)}}else this.mouseX=this.mouseY=null};b._updateMousePosition=function(a,b){var c=this.canvas;do a-=c.offsetLeft,b-=c.offsetTop;while(c=c.offsetParent);if(this.mouseInBounds=a>=0&&b>=0&&a<this.canvas.width&&b<this.canvas.height)this.mouseX=a,this.mouseY=b};b._handleMouseUp=function(a){var b=new EaselMouseEvent("onMouseUp",this.mouseX,this.mouseY);b.nativeEvent=a;if(this.onMouseUp)this.onMouseUp(b);
if(this._activeMouseEvent&&this._activeMouseEvent.onMouseUp)this._activeMouseEvent.onMouseUp(b);if(this._activeMouseTarget&&this._activeMouseTarget.onClick&&this._getObjectsUnderPoint(this.mouseX,this.mouseY,null,!0,this._mouseOverIntervalID?3:1)==this._activeMouseTarget)b=new EaselMouseEvent("onClick",this.mouseX,this.mouseY),b.nativeEvent=a,this._activeMouseTarget.onClick(b);this._activeEaselMouseEvent=this.activeMouseTarget=null};b._handleMouseDown=function(a){var b;if(this.onMouseDown)b=new EaselMouseEvent("onMouseDown",
this.mouseX,this.mouseY),b.nativeEvent=a,this.onMouseDown(b);var c=this._getObjectsUnderPoint(this.mouseX,this.mouseY,null,this._mouseOverIntervalID?3:1);if(c){if(c.onPress instanceof Function&&(b=new EaselMouseEvent("onPress",this.mouseX,this.mouseY),b.nativeEvent=a,c.onPress(b),b.onMouseMove||b.onMouseUp))this._activeEaselMouseEvent=b;this._activeMouseTarget=c}};b._testMouseOver=function(){if(!(this.mouseX==this._mouseOverX&&this.mouseY==this._mouseOverY&&this.mouseInBounds)){var a=null;if(this.mouseInBounds)a=
this._getObjectsUnderPoint(this.mouseX,this.mouseY,null,3),this._mouseOverX=this.mouseX,this._mouseOverY=this.mouseY;if(this._mouseOverTarget!=a){if(this._mouseOverTarget&&this._mouseOverTarget.onMouseOut)this._mouseOverTarget.onMouseOut(new EaselMouseEvent("onMouseOver",this.mouseX,this.mouseY));if(a&&a.onMouseOver)a.onMouseOver(new EaselMouseEvent("onMouseOut",this.mouseX,this.mouseY));this._mouseOverTarget=a}}};b._handleDoubleClick=function(a){var b;if(this.onDoubleClick)b=new EaselMouseEvent("onDoubleClick",
this.mouseX,this.mouseY),b.nativeEvent=a,this.onDoubleClick(b);var c=this._getObjectsUnderPoint(this.mouseX,this.mouseY,null,this._mouseOverIntervalID?3:1);if(c&&c.onDoubleClick instanceof Function)b=new EaselMouseEvent("onPress",this.mouseX,this.mouseY),b.nativeEvent=a,c.onDoubleClick(b)};k.Stage=Stage})(window);(function(k){Bitmap=function(a){this.initialize(a)};var b=Bitmap.prototype=new DisplayObject;b.image=null;b.snapToPixel=!0;b.DisplayObject_initialize=b.initialize;b.initialize=function(a){this.DisplayObject_initialize();this.image=a};b.isVisible=function(){return this.visible&&this.alpha>0&&this.scaleX!=0&&this.scaleY!=0&&this.image&&(this.image.complete||this.image.getContext)};b.DisplayObject_draw=b.draw;b.draw=function(a,b){if(this.DisplayObject_draw(a,b))return!0;a.drawImage(this.image,0,0);return!0};
b.clone=function(){var a=new Bitmap(this.image);this.cloneProps(a);return a};b.toString=function(){return"[Bitmap (name="+this.name+")]"};k.Bitmap=Bitmap})(window);(function(k){BitmapSequence=function(a){this.initialize(a)};var b=BitmapSequence.prototype=new DisplayObject;b.callback=null;b.currentFrame=-1;b.currentSequence=null;b.currentEndFrame=null;b.currentStartFrame=null;b.nextSequence=null;b.paused=!1;b.spriteSheet=null;b.snapToPixel=!0;b.DisplayObject_initialize=b.initialize;b.initialize=function(a){this.DisplayObject_initialize();this.spriteSheet=a};b.isVisible=function(){var a=this.spriteSheet?this.spriteSheet.image:null;return this.visible&&this.alpha>
0&&this.scaleX!=0&&this.scaleY!=0&&a&&this.currentFrame>=0&&(a.complete||a.getContext)};b.DisplayObject_draw=b.draw;b.draw=function(a,b){if(this.DisplayObject_draw(a,b))return!0;var c=this.spriteSheet.image,d=this.spriteSheet.frameWidth,e=this.spriteSheet.frameHeight,f=c.width/d|0,g=c.height/e|0;if(this.currentEndFrame!=null){if(this.currentFrame>this.currentEndFrame)this.nextSequence?this._goto(this.nextSequence):(this.paused=!0,this.currentFrame=this.currentEndFrame),this.callback&&this.callback(this)}else if(g=
this.spriteSheet.totalFrames||f*g,this.currentFrame>=g)this.spriteSheet.loop?this.currentFrame=0:(this.currentFrame=g-1,this.paused=!0),this.callback&&this.callback(this);this.currentFrame>=0&&a.drawImage(c,d*(this.currentFrame%f),e*(this.currentFrame/f|0),d,e,0,0,d,e);return!0};b.tick=function(){if(this.currentFrame==-1&&this.spriteSheet.frameData)this.paused=!0;this.paused||this.currentFrame++};b.gotoAndPlay=function(a){this.paused=!1;this._goto(a)};b.gotoAndStop=function(a){this.paused=!0;this._goto(a)};
b.clone=function(){var a=new BitmapSequence(this.spriteSheet);this.cloneProps(a);return a};b.toString=function(){return"[BitmapSequence (name="+this.name+")]"};b.DisplayObject_cloneProps=b.cloneProps;b.cloneProps=function(a){this.DisplayObject_cloneProps(a);a.callback=this.callback;a.currentFrame=this.currentFrame;a.currentStartFrame=this.currentStartFrame;a.currentEndFrame=this.currentEndFrame;a.currentSequence=this.currentSequence;a.nextSequence=this.nextSequence;a.paused=this.paused;a.frameData=
this.frameData};b._goto=function(a){if(isNaN(a))if(a==this.currentSequence)this.currentFrame=this.currentStartFrame;else{var b=this.spriteSheet.frameData[a];if(b instanceof Array){this.currentFrame=this.currentStartFrame=b[0];this.currentSequence=a;this.currentEndFrame=b[1];if(this.currentEndFrame==null)this.currentEndFrame=this.currentStartFrame;if(this.currentEndFrame==null)this.currentEndFrame=this.currentFrame;this.nextSequence=b[2];if(this.nextSequence==null)this.nextSequence=this.currentSequence;
else if(this.nextSequence==!1)this.nextSequence=null}else this.currentSequence=this.nextSequence=null,this.currentEndFrame=this.currentFrame=this.currentStartFrame=b}else this.currentSequence=this.nextSequence=this.currentEndFrame=null,this.currentStartFrame=0,this.currentFrame=a};k.BitmapSequence=BitmapSequence})(window);(function(k){Shape=function(a){this.initialize(a)};var b=Shape.prototype=new DisplayObject;b.graphics=null;b.DisplayObject_initialize=b.initialize;b.initialize=function(a){this.DisplayObject_initialize();this.graphics=a?a:new Graphics};b.isVisible=function(){return this.visible&&this.alpha>0&&this.scaleX!=0&&this.scaleY!=0&&this.graphics};b.DisplayObject_draw=b.draw;b.draw=function(a,b){if(this.DisplayObject_draw(a,b))return!0;this.graphics.draw(a);return!0};b.clone=function(a){a=new Shape(a&&this.graphics?
this.graphics.clone():this.graphics);this.cloneProps(a);return a};b.toString=function(){return"[Shape (name="+this.name+")]"};k.Shape=Shape})(window);(function(k){DisplayText=function(a,b,c){this.initialize(a,b,c)};var b=DisplayText.prototype=new DisplayObject;DisplayText._workingContext=document.createElement("canvas").getContext("2d");b.text="";b.font=null;b.color=null;b.textAlign=null;b.textBaseline=null;b.maxWidth=null;b.outline=!1;b.lineHeight=null;b.lineWidth=null;b.DisplayObject_initialize=b.initialize;b.initialize=function(a,b,c){this.DisplayObject_initialize();this.text=a;this.font=b;this.color=c?c:"#000"};b.isVisible=function(){return Boolean(this.visible&&
this.alpha>0&&this.scaleX!=0&&this.scaleY!=0&&this.text!=null&&this.text!="")};b.DisplayObject_draw=b.draw;b.draw=function(a,b){if(this.DisplayObject_draw(a,b))return!0;this.outline?a.strokeStyle=this.color:a.fillStyle=this.color;a.font=this.font;a.textAlign=this.textAlign?this.textAlign:"start";a.textBaseline=this.textBaseline?this.textBaseline:"alphabetic";for(var c=String(this.text).split(/(?:\r\n|\r|\n)/),d=this.lineHeight==null?this.getMeasuredLineHeight():this.lineHeight,e=0,f=0,g=c.length;f<
g;f++){var h=a.measureText(c[f]).width;if(this.lineWidth==null||h<this.lineWidth)this._drawTextLine(a,c[f],e);else{h=c[f].split(/(\s)/);for(var i=h[0],j=1,k=h.length;j<k;j+=2)a.measureText(i+h[j]+h[j+1]).width>this.lineWidth?(this._drawTextLine(a,i,e),e+=d,i=h[j+1]):i+=h[j]+h[j+1];this._drawTextLine(a,i,e)}e+=d}return!0};b.getMeasuredWidth=function(){return this._getWorkingContext().measureText(this.text).width};b.getMeasuredLineHeight=function(){return this._getWorkingContext().measureText("M").width*
1.2};b.clone=function(){var a=new DisplayText(this.text,this.font,this.color);this.cloneProps(a);return a};b.toString=function(){return"[DisplayText (text="+(this.text.length>20?this.text.substr(0,17)+"...":this.text)+")]"};b.DisplayObject_cloneProps=b.cloneProps;b.cloneProps=function(a){this.DisplayObject_cloneProps(a);a.textAlign=this.textAlign;a.textBaseline=this.textBaseline;a.maxWidth=this.maxWidth;a.outline=this.outline;a.lineHeight=this.lineHeight;a.lineWidth=this.lineWidth};b._getWorkingContext=
function(){var a=DisplayText._workingContext;a.font=this.font;a.textAlign=this.textAlign?this.textAlign:"start";a.textBaseline=this.textBaseline?this.textBaseline:"alphabetic";return a};b._drawTextLine=function(a,b,c){this.outline?a.strokeText(b,0,c,this.maxWidth):a.fillText(b,0,c,this.maxWidth)};k.DisplayText=DisplayText})(window);(function(k){SpriteSheetUtils=function(){throw"SpriteSheetUtils cannot be instantiated";};SpriteSheetUtils._workingCanvas=document.createElement("canvas");SpriteSheetUtils._workingContext=SpriteSheetUtils._workingCanvas.getContext("2d");SpriteSheetUtils.flip=function(b,a){var k=b.image,c=b.frameData,d=b.frameWidth,e=b.frameHeight,f=k.width/d|0,g=k.height/e|0,h=f*g,i={},j,m;for(m in c)j=c[m],j instanceof Array&&(j=j.slice(0)),i[m]=j;var q=[],n=0,l=0;for(m in a)if(j=a[m],j=c[j[0]],j!=null){if(j instanceof
Array){var r=j[0],p=j[1];p==null&&(p=r)}else r=p=j;q[l]=m;q[l+1]=r;q[l+2]=p;n+=p-r+1;l+=4}c=SpriteSheetUtils._workingCanvas;c.width=k.width;c.height=Math.ceil(g+n/f)*e;n=SpriteSheetUtils._workingContext;n.drawImage(k,0,0,f*d,g*e,0,0,f*d,g*e);g=h-1;for(l=0;l<q.length;l+=4){m=q[l];r=q[l+1];p=q[l+2];j=a[m];h=j[1]?-1:1;for(var t=j[2]?-1:1,u=h==-1?d:0,v=t==-1?e:0,s=r;s<=p;s++)g++,n.save(),n.translate(g%f*d+u,(g/f|0)*e+v),n.scale(h,t),n.drawImage(k,s%f*d,(s/f|0)*e,d,e,0,0,d,e),n.restore();i[m]=[g-(p-r),
g,j[3]]}k=new Image;k.src=c.toDataURL("image/png");return new SpriteSheet(k.width>0?k:c,d,e,i)};SpriteSheetUtils.frameDataToString=function(b){var a="",k=0,c=0,d=0,e,f;for(f in b){d++;e=b[f];if(e instanceof Array){var g=e[0],h=e[1];h==null&&(h=g);e=e[2];e==null&&(e=f)}else g=h=e,e=f;a+="\n\t"+f+", start="+g+", end="+h+", next="+e;e==!1?a+=" (stop)":e==f&&(a+=" (loop)");h>k&&(k=h);g<c&&(c=g)}return d+" sequences, min="+c+", max="+k+a};SpriteSheetUtils.extractFrame=function(b,a){var k=b.image,c=b.frameWidth,
d=b.frameHeight,e=k.width/c|0;if(isNaN(a)){var f=b.frameData[a];a=f instanceof Array?f[0]:f}f=SpriteSheetUtils._workingCanvas;f.width=c;f.height=d;SpriteSheetUtils._workingContext.drawImage(k,a%e*c,(a/e|0)*d,c,d,0,0,c,d);k=new Image;k.src=f.toDataURL("image/png");return k};k.SpriteSheetUtils=SpriteSheetUtils})(window);
